/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsNameRouteImport } from './routes/plugins.$name'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsNameRoute = PluginsNameRouteImport.update({
  id: '/plugins/$name',
  path: '/plugins/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/debug': typeof DebugRoute
  '/events': typeof EventsRoute
  '/integrations': typeof IntegrationsRoute
  '/playground': typeof PlaygroundRoute
  '/portal': typeof PortalRoute
  '/plugins/$name': typeof PluginsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/debug': typeof DebugRoute
  '/events': typeof EventsRoute
  '/integrations': typeof IntegrationsRoute
  '/playground': typeof PlaygroundRoute
  '/portal': typeof PortalRoute
  '/plugins/$name': typeof PluginsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/debug': typeof DebugRoute
  '/events': typeof EventsRoute
  '/integrations': typeof IntegrationsRoute
  '/playground': typeof PlaygroundRoute
  '/portal': typeof PortalRoute
  '/plugins/$name': typeof PluginsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/apps'
    | '/chat'
    | '/debug'
    | '/events'
    | '/integrations'
    | '/playground'
    | '/portal'
    | '/plugins/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/apps'
    | '/chat'
    | '/debug'
    | '/events'
    | '/integrations'
    | '/playground'
    | '/portal'
    | '/plugins/$name'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/apps'
    | '/chat'
    | '/debug'
    | '/events'
    | '/integrations'
    | '/playground'
    | '/portal'
    | '/plugins/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AppsRoute: typeof AppsRoute
  ChatRoute: typeof ChatRoute
  DebugRoute: typeof DebugRoute
  EventsRoute: typeof EventsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PortalRoute: typeof PortalRoute
  PluginsNameRoute: typeof PluginsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$name': {
      id: '/plugins/$name'
      path: '/plugins/$name'
      fullPath: '/plugins/$name'
      preLoaderRoute: typeof PluginsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AppsRoute: AppsRoute,
  ChatRoute: ChatRoute,
  DebugRoute: DebugRoute,
  EventsRoute: EventsRoute,
  IntegrationsRoute: IntegrationsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PortalRoute: PortalRoute,
  PluginsNameRoute: PluginsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
