import { Page } from 'puppeteer';
import { Chat, LiveLocationChangedEvent, ChatState, ChatMuteDuration, GroupChatCreationResponse, EphemeralDuration } from './model/chat';
import { BusinessProfile, Contact, NumberCheck } from './model/contact';
import { Message, MessageInfo, MessagePinDuration, PollData } from './model/message';
import { AxiosRequestConfig } from 'axios';
import { NewCommunityGroup, ParticipantChangedEventModel, GenericGroupChangeEvent, GroupMetadata } from './model/group-metadata';
import { ConfigObject, STATE, LicenseType, Webhook, EventPayload } from './model';
import PQueue, { DefaultAddOptions, Options } from 'p-queue';
import { HealthCheck, SessionInfo } from './model/sessionInfo';
import { ChatId, GroupChatId, Content, Base64, MessageId, ContactId, DataURL, AdvancedFile, GroupId } from './model/aliases';
import { CustomProduct, Order, Product } from './model/product';
import { Label } from './model/label';
import { Mp4StickerConversionProcessOptions, StickerMetadata } from './model/media';
import { SimpleListener } from './model/events';
import { AwaitMessagesOptions, Collection, CollectorFilter, CollectorOptions } from '../structures/Collector';
import { MessageCollector } from '../structures/MessageCollector';
import { Listener } from 'eventemitter2';
import PriorityQueue from 'p-queue/dist/priority-queue';
import { NextFunction, Request, Response } from 'express';
import { Call } from './model/call';
import { AdvancedButton, Button, LocationButtonBody, Section } from './model/button';
import { JsonObject } from 'type-fest';
import { ReactionEvent } from './model/reactions';
export declare enum namespace {
    Chat = "Chat",
    Msg = "Msg",
    Contact = "Contact",
    GroupMetadata = "GroupMetadata"
}
export declare class Client {
    private _loadedModules;
    private _registeredWebhooks;
    private _registeredEvListeners;
    private _webhookQueue;
    private _createConfig;
    private _sessionInfo;
    private _listeners;
    private _page;
    private _currentlyBeingKilled;
    private _refreshing;
    private _loaded;
    private _hostAccountNumber;
    private _prio;
    private _pageListeners;
    private _registeredPageListeners;
    private _onLogoutCallbacks;
    private _queues;
    private _autoEmojiSet;
    private _autoEmojiQ;
    private _onLogoutSet;
    private _preprocIdempotencyCheck;
    private _registeredWebhookListeners;
    constructor(page: Page, createConfig: ConfigObject, sessionInfo: SessionInfo);
    loaded(): Promise<void>;
    private registerAllSimpleListenersOnEv;
    getSessionId(): string;
    getPage(): Page;
    private _setOnClose;
    private _reInjectWapi;
    private _reRegisterListeners;
    download(url: string, optionsOverride?: any): Promise<DataURL>;
    logger(): any;
    refresh(): Promise<boolean>;
    getSessionInfo(): SessionInfo;
    resizePage(width?: number, height?: number): Promise<boolean>;
    getConfig(): ConfigObject;
    private pup;
    private responseWrap;
    removeListener(listener: SimpleListener): boolean;
    removeAllListeners(): boolean;
    private registerListener;
    private registerPageEventListener;
    gc(): Promise<void>;
    onLogout(fn: (loggedOut?: boolean) => any, priority?: number): Promise<boolean>;
    waitWhQIdle(): Promise<true | void>;
    waitAllQEmpty(): Promise<true | void[]>;
    getListenerQueues(): {
        [key in SimpleListener]?: PQueue;
    };
    private preprocessMessage;
    onMessage(fn: (message: Message) => void, queueOptions?: Options<PriorityQueue, DefaultAddOptions>): Promise<Listener | boolean>;
    onAnyMessage(fn: (message: Message) => void, queueOptions?: Options<PriorityQueue, DefaultAddOptions>): Promise<Listener | boolean>;
    onMessageDeleted(fn: (message: Message) => void): Promise<Listener | boolean>;
    onChatDeleted(fn: (chat: Chat) => void): Promise<Listener | boolean>;
    onButton(fn: (message: Message) => void): Promise<Listener | boolean>;
    onPollVote(fn: (pollDate: PollData) => void): Promise<Listener | boolean>;
    onBroadcast(fn: (message: Message) => void): Promise<Listener | boolean>;
    onBattery(fn: (battery: number) => void): Promise<Listener | boolean>;
    onPlugged(fn: (plugged: boolean) => void): Promise<Listener | boolean>;
    onStory(fn: (story: Message) => void): Promise<Listener | boolean>;
    onStateChanged(fn: (state: STATE) => void): Promise<Listener | boolean>;
    onIncomingCall(fn: (call: Call) => void): Promise<Listener | boolean>;
    onCallState(fn: (call: Call) => void): Promise<Listener | boolean>;
    onLabel(fn: (label: Label) => void): Promise<Listener | boolean>;
    onOrder(fn: (order: Order) => void): Promise<Listener | boolean>;
    onNewProduct(fn: (product: Product) => void): Promise<Listener | boolean>;
    onReaction(fn: (reactionEvent: ReactionEvent) => void): Promise<Listener | boolean>;
    onChatState(fn: (chatState: ChatState) => void): Promise<Listener | boolean>;
    onAck(fn: (message: Message) => void): Promise<Listener | boolean>;
    onGlobalParticipantsChanged(fn: (participantChangedEvent: ParticipantChangedEventModel) => void): Promise<Listener | boolean>;
    onGroupApprovalRequest(fn: (groupApprovalRequestMessage: Message) => void): Promise<Listener | boolean>;
    onGroupChange(fn: (genericGroupChangeEvent: GenericGroupChangeEvent) => void): Promise<Listener | boolean>;
    onAddedToGroup(fn: (chat: Chat) => any): Promise<Listener | boolean>;
    onRemovedFromGroup(fn: (chat: Chat) => any): Promise<Listener | boolean>;
    onChatOpened(fn: (chat: Chat) => any): Promise<Listener | boolean>;
    onContactAdded(fn: (chat: Chat) => any): Promise<Listener | boolean>;
    onParticipantsChanged(groupId: GroupChatId, fn: (participantChangedEvent: ParticipantChangedEventModel) => void, legacy?: boolean): Promise<Listener | boolean>;
    onLiveLocation(chatId: ChatId, fn: (liveLocationChangedEvent: LiveLocationChangedEvent) => void): Promise<boolean>;
    testCallback(callbackToTest: SimpleListener, testData: any): Promise<boolean>;
    setPresence(available: boolean): Promise<boolean | void>;
    setMyStatus(newStatus: string): Promise<boolean | void>;
    createLabel(label: string): Promise<string | boolean>;
    addLabel(label: string, chatId: ChatId): Promise<boolean>;
    getAllLabels(): Promise<Label[]>;
    removeLabel(label: string, chatId: ChatId): Promise<boolean>;
    getChatsByLabel(label: string): Promise<Chat[]>;
    sendVCard(chatId: ChatId, vcard: string, contactName?: string, contactNumber?: string): Promise<boolean>;
    setMyName(newName: string): Promise<boolean>;
    setChatState(chatState: ChatState, chatId: ChatId): Promise<boolean>;
    getConnectionState(): Promise<STATE>;
    getUnsentMessages(): Promise<Message[]>;
    forceUpdateConnectionState(killBeforeReconnect?: boolean): Promise<STATE>;
    getChatWithNonContacts(): Promise<Contact[]>;
    kill(reason?: string): Promise<boolean>;
    forceRefocus(): Promise<boolean>;
    isPhoneDisconnected(): Promise<boolean>;
    healthCheck(): Promise<HealthCheck>;
    getProcessStats(): Promise<any>;
    forceUpdateLiveLocation(chatId: ChatId): Promise<LiveLocationChangedEvent[] | boolean>;
    testButtons(chatId: ChatId): Promise<any>;
    private link;
    getLicenseLink(params?: string): Promise<string>;
    sendText(to: ChatId, content: Content): Promise<boolean | MessageId>;
    sendTextWithMentions(to: ChatId, content: Content, hideTags?: boolean, mentions?: ContactId[]): Promise<boolean | MessageId>;
    editMessage(messageId: MessageId, text: Content): Promise<boolean | MessageId>;
    sendPaymentRequest(to: ChatId, amount: number, currency: string, message?: string): Promise<boolean | MessageId>;
    sendButtons(to: ChatId, body: string | LocationButtonBody, buttons: Button[], title?: string, footer?: string): Promise<boolean | MessageId>;
    sendAdvancedButtons(to: ChatId, body: string | LocationButtonBody, buttons: AdvancedButton[], text: string, footer: string, filename: string): Promise<boolean | MessageId>;
    sendBanner(to: ChatId, base64: Base64): Promise<boolean | MessageId>;
    sendListMessage(to: ChatId, sections: Section[], title: string, description: string, actionText: string): Promise<boolean | MessageId>;
    sendReplyWithMentions(to: ChatId, content: Content, replyMessageId: MessageId, hideTags?: boolean, mentions?: ContactId[]): Promise<boolean | MessageId>;
    tagEveryone(groupId: GroupChatId, content: Content, hideTags?: boolean, formatting?: string, messageBeforeTags?: boolean): Promise<boolean | MessageId>;
    sendMessageWithThumb(thumb: string, url: string, title: string, description: string, text: Content, chatId: ChatId, quotedMsgId?: MessageId, customSize?: {
        height: number;
        width: number;
    }): Promise<MessageId | boolean>;
    sendLocation(to: ChatId, lat: string, lng: string, loc: string, address?: string, url?: string): Promise<boolean | MessageId>;
    getGeneratedUserAgent(userA?: string): Promise<string>;
    decryptMedia(message: Message | MessageId): Promise<DataURL>;
    sendImage(to: ChatId, file: AdvancedFile, filename: string, caption: Content, quotedMsgId?: MessageId, waitForId?: boolean, ptt?: boolean, withoutPreview?: boolean, hideTags?: boolean, viewOnce?: boolean, requestConfig?: any): Promise<MessageId | boolean>;
    sendYoutubeLink(to: ChatId, url: string, text?: Content, thumbnail?: Base64, quotedMsgId?: MessageId, customSize?: {
        height: number;
        width: number;
    }): Promise<boolean | MessageId>;
    sendLinkWithAutoPreview(to: ChatId, url: string, text?: Content, thumbnail?: Base64, quotedMsgId?: MessageId, customSize?: {
        height: number;
        width: number;
    }): Promise<boolean | MessageId>;
    reply(to: ChatId, content: Content, quotedMsgId: MessageId, sendSeen?: boolean): Promise<boolean | MessageId>;
    checkReadReceipts(contactId: ContactId): Promise<string | boolean>;
    sendFile(to: ChatId, file: AdvancedFile, filename: string, caption: Content, quotedMsgId?: MessageId, waitForId?: boolean, ptt?: boolean, withoutPreview?: boolean, hideTags?: boolean, viewOnce?: boolean, requestConfig?: any): Promise<MessageId | boolean>;
    isGroupIdUnsafe(groupChatId: GroupChatId): Promise<string | boolean>;
    sendPtt(to: ChatId, file: AdvancedFile, quotedMsgId?: MessageId): Promise<MessageId>;
    sendAudio(to: ChatId, file: AdvancedFile, quotedMsgId?: MessageId): Promise<MessageId>;
    sendPoll(to: GroupChatId, name: string, options: string[], quotedMsgId?: MessageId, allowMultiSelect?: boolean): Promise<MessageId>;
    sendVideoAsGif(to: ChatId, file: AdvancedFile, filename: string, caption: Content, quotedMsgId?: MessageId, requestConfig?: AxiosRequestConfig): Promise<MessageId>;
    sendGiphy(to: ChatId, giphyMediaUrl: string, caption: Content): Promise<MessageId>;
    sendFileFromUrl(to: ChatId, url: string, filename: string, caption: Content, quotedMsgId?: MessageId, requestConfig?: AxiosRequestConfig, waitForId?: boolean, ptt?: boolean, withoutPreview?: boolean, hideTags?: boolean, viewOnce?: boolean): Promise<MessageId | boolean>;
    getMe(): Promise<any>;
    getFeatures(): Promise<any>;
    getSnapshot(chatId?: ChatId, width?: number, height?: number): Promise<DataURL>;
    metrics(): Promise<any>;
    iAmAdmin(): Promise<GroupChatId[]>;
    getKickedGroups(): Promise<GroupChatId[]>;
    syncContacts(): Promise<boolean>;
    getAmountOfLoadedMessages(): Promise<number>;
    getBusinessProfilesProducts(id: ContactId): Promise<any>;
    getBusinessProfile(id: ContactId): Promise<BusinessProfile>;
    sendImageWithProduct(to: ChatId, image: Base64, caption: Content, bizNumber: ContactId, productId: string): Promise<boolean | MessageId>;
    sendCustomProduct(to: ChatId, image: DataURL, productData: CustomProduct): Promise<MessageId | boolean>;
    sendContact(to: ChatId, contactId: ContactId | ContactId[]): Promise<MessageId | boolean>;
    sendMultipleContacts(to: ChatId, contactIds: ContactId[]): Promise<MessageId | boolean>;
    simulateTyping(to: ChatId, on: boolean): Promise<boolean>;
    simulateRecording(to: ChatId, on: boolean): Promise<boolean>;
    archiveChat(id: ChatId, archive: boolean): Promise<boolean>;
    pinChat(id: ChatId, pin: boolean): Promise<boolean>;
    pinMessage(id: MessageId, pin: boolean, pinDuration?: MessagePinDuration): Promise<boolean>;
    keepMessage(id: MessageId, keep: boolean): Promise<boolean>;
    muteChat(chatId: ChatId, muteDuration: ChatMuteDuration): Promise<boolean | string | number>;
    isChatMuted(chatId: ChatId): Promise<boolean>;
    unmuteChat(chatId: ChatId): Promise<boolean | string | number>;
    forwardMessages(to: ChatId, messages: MessageId | MessageId[], skipMyMessages: boolean): Promise<boolean | MessageId[]>;
    ghostForward(to: ChatId, messageId: MessageId): Promise<MessageId | boolean>;
    getAllContacts(): Promise<Contact[]>;
    getWAVersion(): Promise<string>;
    getIssueLink(): Promise<string>;
    isConnected(): Promise<boolean>;
    logout(preserveSessionData?: boolean): Promise<boolean>;
    getBatteryLevel(): Promise<number>;
    getIsPlugged(): Promise<boolean>;
    getHostNumber(): Promise<string>;
    getLicenseType(): Promise<LicenseType | false>;
    getTunnelCode(): Promise<string>;
    getLastMsgTimestamps(): Promise<{
        id: ChatId;
        t: number;
    }[]>;
    getAllChats(withNewMessageOnly?: boolean): Promise<Chat[]>;
    getAllChatIds(): Promise<ChatId[]>;
    getBlockedIds(): Promise<ChatId[]>;
    getAllChatsWithMessages(withNewMessageOnly?: boolean): Promise<Chat[]>;
    getGptArray(chatId: ChatId, last?: number): Promise<{
        role: "user" | "assistant";
        content: string;
    }[]>;
    getAllGroups(withNewMessagesOnly?: boolean): Promise<Chat[]>;
    getAllCommunities(): Promise<GroupId[]>;
    getGroupMembersId(groupId: GroupChatId): Promise<ContactId[]>;
    getGroupInfo(groupId: GroupChatId): Promise<any>;
    getCommunityInfo(communityId: GroupChatId): Promise<GroupMetadata & {
        subGroups: GroupMetadata[];
    }>;
    acceptGroupJoinRequest(messageId: MessageId): Promise<boolean>;
    getCommunityParticipantIds(communityId: GroupChatId): Promise<{
        id: GroupChatId;
        participants: ContactId[];
        subgroup: boolean;
    }[]>;
    getCommunityAdminIds(communityId: GroupChatId): Promise<{
        id: GroupChatId;
        admins: ContactId[];
        subgroup: boolean;
    }[]>;
    getCommunityParticipants(communityId: GroupChatId): Promise<{
        id: GroupChatId;
        participants: Contact[];
        subgroup: boolean;
    }[]>;
    getCommunityAdmins(communityId: GroupChatId): Promise<{
        id: GroupChatId;
        admins: Contact[];
        subgroup: boolean;
    }[]>;
    joinGroupViaLink(link: string, returnChatObj?: boolean): Promise<string | boolean | number | Chat>;
    contactBlock(id: ContactId): Promise<boolean>;
    reportSpam(id: ContactId | ChatId): Promise<boolean>;
    contactUnblock(id: ContactId): Promise<boolean>;
    leaveGroup(groupId: GroupChatId): Promise<boolean>;
    getVCards(msgId: MessageId): Promise<string[]>;
    getGroupMembers(groupId: GroupChatId): Promise<Contact[]>;
    getContact(contactId: ContactId): Promise<Contact>;
    getChatById(contactId: ContactId): Promise<Chat>;
    getMessageById(messageId: MessageId): Promise<Message>;
    getMessageInfo(messageId: MessageId): Promise<MessageInfo>;
    getOrder(id: MessageId | string): Promise<Order>;
    createNewProduct(name: string, price: number, currency: string, images: string[], description: string, url?: string, internalId?: string, isHidden?: boolean): Promise<Product>;
    editProduct(productId: string, name?: string, price?: number, currency?: string, images?: DataURL[], description?: string, url?: string, internalId?: string, isHidden?: boolean): Promise<Product>;
    sendProduct(chatId: ChatId, productId: string): Promise<MessageId>;
    removeProduct(productId: string): Promise<boolean>;
    getMyLastMessage(chatId?: ChatId): Promise<Message | undefined>;
    getStarredMessages(chatId?: ChatId): Promise<Message[]>;
    starMessage(messageId: MessageId): Promise<boolean>;
    unstarMessage(messageId: MessageId): Promise<boolean>;
    react(messageId: MessageId, emoji: string): Promise<boolean>;
    getStickerDecryptable(messageId: MessageId): Promise<Message | false>;
    forceStaleMediaUpdate(messageId: MessageId): Promise<Message | false>;
    getChat(contactId: ContactId): Promise<Chat>;
    getCommonGroups(contactId: ContactId): Promise<{
        id: string;
        title: string;
    }[]>;
    getLastSeen(chatId: ChatId): Promise<number | boolean>;
    getProfilePicFromServer(chatId: ChatId): Promise<string>;
    sendSeen(chatId: ChatId): Promise<boolean>;
    markAllRead(): Promise<boolean>;
    markAsUnread(chatId: ChatId): Promise<boolean>;
    isChatOnline(chatId: ChatId): Promise<boolean | string>;
    loadEarlierMessages(contactId: ContactId): Promise<Message[]>;
    getStatus(contactId: ContactId): Promise<{
        id: string;
        status: string;
    }>;
    B(chatId: ChatId, payload: {
        [k: string]: any;
    }): Promise<MessageId>;
    loadAllEarlierMessages(contactId: ContactId): Promise<Message[]>;
    loadEarlierMessagesTillDate(contactId: ContactId, timestamp: number): Promise<Message[]>;
    deleteChat(chatId: ChatId): Promise<boolean>;
    clearChat(chatId: ChatId): Promise<boolean>;
    getGroupInviteLink(chatId: ChatId): Promise<string>;
    inviteInfo(link: string): Promise<any>;
    favSticker(msgId: MessageId, fav?: boolean): Promise<string>;
    sendFavSticker(chatId: ChatId, favId: string): Promise<MessageId>;
    getFavStickers(): Promise<Partial<Message>>;
    revokeGroupInviteLink(chatId: ChatId): Promise<boolean | string>;
    getGroupApprovalRequests(groupChatId: GroupChatId): Promise<ContactId[]>;
    approveGroupJoinRequest(groupChatId: GroupChatId, contactId: ContactId): Promise<boolean | string>;
    rejectGroupJoinRequest(groupChatId: GroupChatId, contactId: ContactId): Promise<boolean | string>;
    deleteMessage(chatId: ChatId, messageId: MessageId[] | MessageId, onlyLocal?: boolean): Promise<void>;
    checkNumberStatus(contactId: ContactId): Promise<NumberCheck>;
    getUnreadMessages(includeMe: boolean, includeNotifications: boolean, use_unread_count: boolean): Promise<Chat & {
        messages: Message[];
    }[]>;
    getAllNewMessages(): Promise<Message[]>;
    getAllUnreadMessages(): Promise<Message[]>;
    getIndicatedNewMessages(): Promise<Message[]>;
    emitUnreadMessages(): Promise<MessageId[]>;
    getAllMessagesInChat(chatId: ChatId, includeMe: boolean, includeNotifications: boolean): Promise<Message[]>;
    loadAndGetAllMessagesInChat(chatId: ChatId, includeMe: boolean, includeNotifications: boolean): Promise<Message[]>;
    createGroup(groupName: string, contacts: ContactId | ContactId[]): Promise<GroupChatCreationResponse>;
    createCommunity(communityName: string, communitySubject: string, icon: DataURL, existingGroups?: GroupChatId[], newGroups?: NewCommunityGroup[]): Promise<GroupId>;
    removeParticipant(groupId: GroupChatId, participantId: ContactId): Promise<boolean>;
    setGroupIcon(groupId: GroupChatId, image: DataURL): Promise<boolean>;
    setGroupIconByUrl(groupId: GroupChatId, url: string, requestConfig?: AxiosRequestConfig): Promise<boolean>;
    addParticipant(groupId: GroupChatId, participantId: ContactId | ContactId[]): Promise<boolean>;
    promoteParticipant(groupId: GroupChatId, participantId: ContactId | ContactId[]): Promise<boolean>;
    demoteParticipant(groupId: GroupChatId, participantId: ContactId | ContactId[]): Promise<boolean>;
    setGroupToAdminsOnly(groupId: GroupChatId, onlyAdmins: boolean): Promise<boolean>;
    setGroupEditToAdminsOnly(groupId: GroupChatId, onlyAdmins: boolean): Promise<boolean>;
    setGroupApprovalMode(groupId: GroupChatId, requireApproval: boolean): Promise<boolean>;
    setGroupDescription(groupId: GroupChatId, description: string): Promise<boolean>;
    setGroupTitle(groupId: GroupChatId, title: string): Promise<boolean>;
    getGroupAdmins(groupId: GroupChatId): Promise<ContactId[]>;
    setChatBackgroundColourHex(hex: string): Promise<boolean>;
    joinWebBeta(join: boolean): Promise<boolean>;
    darkMode(activate: boolean): Promise<boolean>;
    autoReject(message?: string): Promise<boolean>;
    getMessageReaders(messageId: MessageId): Promise<Contact[]>;
    getPollData(messageId: MessageId): Promise<PollData>;
    sendStickerfromUrl(to: ChatId, url: string, requestConfig?: AxiosRequestConfig, stickerMetadata?: StickerMetadata): Promise<string | MessageId | boolean>;
    sendStickerfromUrlAsReply(to: ChatId, url: string, messageId: MessageId, requestConfig?: AxiosRequestConfig, stickerMetadata?: StickerMetadata): Promise<MessageId | boolean>;
    sendImageAsStickerAsReply(to: ChatId, image: DataURL | Buffer | Base64 | string, messageId: MessageId, stickerMetadata?: StickerMetadata): Promise<MessageId | boolean | string>;
    getSingleProperty(namespace: namespace, id: string, property: string): Promise<any>;
    private stickerServerRequest;
    private prepareWebp;
    sendImageAsSticker(to: ChatId, image: DataURL | Buffer | Base64 | string, stickerMetadata?: StickerMetadata): Promise<MessageId | string | boolean>;
    sendMp4AsSticker(to: ChatId, file: DataURL | Buffer | Base64 | string, processOptions?: Mp4StickerConversionProcessOptions, stickerMetadata?: StickerMetadata, messageId?: MessageId): Promise<MessageId | string | boolean>;
    sendEmoji(to: ChatId, emojiId: string, messageId?: MessageId): Promise<MessageId | boolean | string>;
    sendRawWebpAsSticker(to: ChatId, webpBase64: Base64, animated?: boolean): Promise<MessageId | string | boolean>;
    sendRawWebpAsStickerAsReply(to: ChatId, messageId: MessageId, webpBase64: Base64, animated?: boolean): Promise<MessageId | string | boolean>;
    setChatEphemeral(chatId: ChatId, ephemeral: EphemeralDuration | boolean): Promise<boolean>;
    sendGiphyAsSticker(to: ChatId, giphyMediaUrl: URL | string): Promise<MessageId | string | boolean>;
    postTextStatus(text: Content, textRgba: string, backgroundRgba: string, font: number): Promise<MessageId | string | boolean>;
    postThumbnailStatus(url: string, text: Content, textRgba: string, backgroundRgba: string, font: number, thumbnail?: Base64): Promise<MessageId>;
    postImageStatus(data: DataURL, caption: Content): Promise<MessageId | string | boolean>;
    postVideoStatus(data: DataURL, caption: Content): Promise<MessageId | string | boolean>;
    deleteStory(statusesToDelete: string | string[]): Promise<boolean>;
    deleteStatus(statusesToDelete: string | string[]): Promise<boolean>;
    deleteAllStories(): Promise<boolean>;
    deleteAllStatus(): Promise<boolean>;
    getMyStoryArray(): Promise<Message[]>;
    getMyStatusArray(): Promise<Message[]>;
    getStoryViewers(id?: string): Promise<ContactId[] | {
        [k: MessageId]: ContactId[];
    }>;
    clearAllChats(ts?: number): Promise<boolean>;
    cutMsgCache(): Promise<number>;
    cutChatCache(): Promise<{
        before: {
            msgs: number;
            chats: number;
        };
        after: {
            msgs: number;
            chats: number;
        };
    }>;
    deleteStaleChats(startingFrom?: number): Promise<boolean>;
    downloadProfilePicFromMessage(message: Message): Promise<Base64>;
    downloadFileWithCredentials(url: string): Promise<Base64>;
    setProfilePic(data: DataURL): Promise<boolean>;
    middleware: (useSessionIdInPath?: boolean, PORT?: number) => (req: Request, res: Response, next: NextFunction) => Promise<any>;
    listWebhooks(): Promise<Webhook[]>;
    removeWebhook(webhookId: string): Promise<boolean>;
    updateWebhook(webhookId: string, events: SimpleListener[] | 'all'): Promise<Webhook | false>;
    private _setupWebhooksOnListeners;
    registerWebhook(url: string, events: SimpleListener[] | 'all', requestConfig?: AxiosRequestConfig, concurrency?: number): Promise<Webhook | false>;
    prepEventData(data: JsonObject, event: SimpleListener, extras?: JsonObject): EventPayload;
    getEventSignature(simpleListener?: SimpleListener): string;
    private registerEv;
    private tickPriority;
    getInstanceId(): string;
    createMessageCollector(c: Message | ChatId | Chat, filter: CollectorFilter<[Message]>, options: CollectorOptions): MessageCollector;
    awaitMessages(c: Message | ChatId | Chat, filter: CollectorFilter<[Message]>, options?: AwaitMessagesOptions): Promise<Collection<string, Message>>;
}
export { useragent } from '../config/puppeteer.config';
//# sourceMappingURL=Client.d.ts.map