# THIS ANSIBLE PLAYBOOK DOES EVERYTHING EXCEPT START THE ORCH PROCESS
# EXAMPLE COMMAND:
# note: if the ssh isn't working then make sure to ssh prior and copy your id rsa pub onto the remote machine
# ansible-playbook -i '11.33.54.39,' -u root -e "npm_u=username npm_p=npm_reg_password npm_e=vtest@email.com owa_id=XQ2USER_IDYH2 owa_secret=bucketsecret" ./ansible.yaml 

---
- hosts: all
  vars:
    pm2_path: /home/admin/orch/node_modules/pm2/bin/
  tasks:
  - name: Ensure user called admin exists
    user:
      name: admin
      group: sudo

  - name: Disable Admin Login
    lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^DenyUsers admin'
          line: "DenyUsers admin"
          state: present
          backup: yes
    become: yes


  - name: Install base dependencies
    apt:
      name:
      - gpg-agent
      - wget
      - curl
      - git
      - nano
      - build-essential
      - gcc
      - g++
      - make
      state: present
      update_cache: yes

  - name: Get DEB architecture
    shell: dpkg --print-architecture
    register: deb_architecture
    
  - name: Install the gpg key for Google Chrome
    apt_key:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      state: present

  - name: Install the gpg key for Cloudflared
    apt_key:
      url: https://pkg.cloudflare.com/cloudflare-main.gpg
      state: present

  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
      # key
  
  # - name: Add cloudflare-main.list to apt sources
  #   apt_repository:
  #     repo: 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/ focal main'
  #     state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_19.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Add google-chrome.list to apt sources
    apt_repository:
      repo: 'deb [arch={{deb_architecture.stdout}}] http://dl.google.com/linux/chrome/deb/ stable main'
      state: present

  - name: Create /sessions directory
    file:
      path: /sessions
      state: directory
      owner: admin
      mode: '0755'

  - name: Install nodejs dependencies
    apt:
      name: nodejs
      state: latest
      update_cache: true


  - name: Download the cloudflared Linux package.
    get_url:
      url: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-{{deb_architecture.stdout}}.deb"
      dest: /
      
  - name: Create a cloudflared service directory.
    file:
      path: /etc/cloudflared/
      state: directory
      owner: admin

  - name: Install cloudflared
    apt:
      deb: "/cloudflared-linux-{{deb_architecture.stdout}}.deb"
  - name: Install dependencies
    apt:
      name:
        - moreutils
        - glances
        - google-chrome-stable
        - gconf-service
        - libasound2
        - libatk1.0-0
        - libatk-bridge2.0-0
        - libc6
        - libcairo2
        - libjemalloc-dev
        - libcups2
        - libdbus-1-3
        - libexpat1
        - libfontconfig1
        - libgcc1
        - libgconf-2-4
        - libgdk-pixbuf2.0-0
        - libglib2.0-0
        - libgtk-3-0
        - libnspr4
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libstdc++6
        - libx11-6
        - libx11-xcb1
        - libxcb1
        - libxcomposite1
        - libxcursor1
        - libxdamage1
        - libxext6
        - libxfixes3
        - libxi6
        - libxrandr2
        - libxrender1
        - libxss1
        - libxtst6
        - ca-certificates
        - fonts-liberation
        - libappindicator1
        - libnss3
        - lsb-release
        - ufw
        - xdg-utils
        - wget
        - libnss3-dev
      state: present
      update_cache: true

  - name: Deny outbound traffic on port 22
    ufw:
      rule: deny
      direction: out
      port: 22
      proto: tcp

  - name: Create /orch directory
    file:
      path: /home/admin/orch
      state: directory
      owner: admin
    become: yes
    become_user: admin

  - name: Install npm, npm-cli-login & cross-env globally
    npm:
      name:  "{{ item }}"
      global: true
    with_items:
      - "npm@latest"
      - npm-cli-login
      - cross-env
      
  # - name: Install npm
  #   npm:
  #     name: "npm@latest"
  #     global: true
  # - name: Install npm-cli-login
  #   npm:
  #     name: npm-cli-login
  #     global: true
  # - name: Install cross-env
  #   npm:
  #     name: cross-env
  #     global: true

  - name: Give ownership of global node_modules to admin user
    file:
      path: "{{ item }}"
      owner: admin
    with_items:
      - /usr/local/lib/node_modules/
      - /usr/lib/node_modules/
    ignore_errors: true

  - name: Give ownership of global bin to admin user
    file:
      path: "{{ item }}"
      owner: admin
    with_items:
      - /usr/local/lib/bin/
      - /usr/lib/bin/
      - /usr/bin/
    ignore_errors: true


  - name: Give ownership of global share to admin user
    file:
      path: "{{ item }}"
      owner: admin
    with_items:
      - /usr/local/lib/share/
      - /usr/lib/share/
      - /usr/share/
    ignore_errors: true

  # - name: Change owner of /usr/local/lib/node_modules/
  #   file:
  #     path: /usr/local/lib/node_modules/
  #     owner: admin

  # - name: Change owner of /usr/local/bin/
  #   file:
  #     path: /usr/local/bin/
  #     owner: admin

  # - name: Change owner of /usr/local/share/
  #   file:
  #     path: /usr/local/share/
  #     owner: admin
      

  - name: Change owner of /home/admin/.npm
    file:
      path: /home/admin/.npm
      state: directory
      owner: admin

  - name: Check if orch folder is already setup
    stat:
      path: /home/admin/orch/package.json
    register: orch_package

  - name: Initialize npm in /home/admin/orch
    command: npm init -y
    args:
      chdir: /home/admin/orch
    when: not orch_package.stat.exists

  - name: Check if authenticated with the custom registry
    command: npm whoami --registry https://registry.openwa.cloud
    ignore_errors: yes
    register: checked_npm_user

  - name: Set @open-wa-enterprise registry in npm
    command: npm config set @open-wa-enterprise:registry https://registry.openwa.cloud
    args:
      chdir: /home/admin/orch
    when: not checked_npm_user.rc == 0

  - name: Login to npm registry
    command: npm-cli-login -u "{{ npm_u }}" -p "{{ npm_p }}" -e "{{ npm_e }}" -r https://registry.openwa.cloud
    when: npm_u is defined and npm_p is defined and npm_e is defined and not checked_npm_user.rc == 0
    args:
      chdir: /home/admin/orch

  - name: Install cross-env
    npm:
      name: "{{ item }}"
      path: /home/admin/orch
      state: "latest"
    with_items:
      - cross-env
      - "@open-wa-enterprise/wa-orchestrate"
      - "@open-wa/wa-automate"
      
  # - name: Install cross-env
  #   npm:
  #     name: cross-env
  #     path: /home/admin/orch

  # - name: Install @open-wa-enterprise/wa-orchestrate
  #   npm:
  #     name: "@open-wa-enterprise/wa-orchestrate"
  #     path: /home/admin/orch
  #     state: "latest"

  # - name: Install @open-wa/wa-automate
  #   npm:
  #     name: "@open-wa/wa-automate"
  #     path: /home/admin/orch
  #     state: "latest"

  - name: Create .env file
    file:
      path: /home/admin/orch/.env
      state: touch
      owner: admin
      modification_time: preserve
      access_time: preserve

  - name: Add USE_CHROME=true to .env
    lineinfile:
      dest: /home/admin/orch/.env
      line: 'USE_CHROME=true'
      state: present

  - name: Add OWA_ID to .env
    lineinfile:
      dest: /home/admin/orch/.env
      line: 'OWA_ID={{ owa_id }}'
      state: present
    when: owa_id is defined

  - name: Add OWA_SECRET to .env
    lineinfile:
      dest: /home/admin/orch/.env
      line: 'OWA_SECRET={{ owa_secret }}'
      state: present
    when: owa_secret is defined

  - name: Find libjemalloc.so
    shell: find /usr/lib/ -maxdepth 2 -name "libjemalloc*.so" 2>/dev/null
    register: jemalloc_path

  - name: Add JEMALLOC_PATH to .env
    lineinfile:
      dest: /home/admin/orch/.env
      line: 'JEMALLOC_PATH={{ jemalloc_path.stdout }}'
      state: present
    when: jemalloc_path.stdout is defined

  - name: add {{pm2_path}} to path
    lineinfile: >
      dest=/etc/environment
      state=present
      backrefs=yes
      regexp='PATH=(["]*)((?!.*?{{pm2_path}}).*?)(["]*)$'
      line="PATH=\1\2:{{pm2_path}}\3"

  - name: Install pm2 log rotate
    shell: "{{pm2_path}}pm2 install pm2-logrotate"
    become: yes
    become_user: admin
    ignore_errors: yes
    args:
      chdir: /home/admin/orch

  - name: Configure pm2 log rotate compression
    shell:  "{{pm2_path}}pm2 set pm2-logrotate:compress true"
    become: yes
    become_user: admin
    ignore_errors: yes
    args:
      chdir: /home/admin/orch

# YOU CAN COMMENT THIS OUT IF YOU DON'T WANT TO AUTOSTART ORCH
  - name: Start orch service, ignore if already running
    shell:  "npx orch"
    become: yes
    become_user: admin
    args:
      chdir: /home/admin/orch
    ignore_errors: yes
