import { Config } from './config';
export declare const ClientConfigSchema: import("zod").ZodObject<{
    sessionData: import("zod").ZodOptional<import("zod").ZodUnion<[import("zod").ZodObject<{
        WABrowserId: import("zod").ZodOptional<import("zod").ZodString>;
        WASecretBundle: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken1: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken2: import("zod").ZodOptional<import("zod").ZodString>;
    }, "passthrough", import("zod").ZodTypeAny, import("zod").objectOutputType<{
        WABrowserId: import("zod").ZodOptional<import("zod").ZodString>;
        WASecretBundle: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken1: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken2: import("zod").ZodOptional<import("zod").ZodString>;
    }, import("zod").ZodTypeAny, "passthrough">, import("zod").objectInputType<{
        WABrowserId: import("zod").ZodOptional<import("zod").ZodString>;
        WASecretBundle: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken1: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken2: import("zod").ZodOptional<import("zod").ZodString>;
    }, import("zod").ZodTypeAny, "passthrough">>, import("zod").ZodString]>>;
    linkCode: import("zod").ZodOptional<import("zod").ZodString>;
    browserWSEndpoint: import("zod").ZodOptional<import("zod").ZodString>;
    useStealth: import("zod").ZodDefault<import("zod").ZodBoolean>;
    sessionDataPath: import("zod").ZodDefault<import("zod").ZodString>;
    bypassCSP: import("zod").ZodDefault<import("zod").ZodBoolean>;
    chromiumArgs: import("zod").ZodOptional<import("zod").ZodArray<import("zod").ZodString, "many">>;
    skipBrokenMethodsCheck: import("zod").ZodDefault<import("zod").ZodBoolean>;
    skipUpdateCheck: import("zod").ZodDefault<import("zod").ZodBoolean>;
    sessionId: import("zod").ZodDefault<import("zod").ZodString>;
    licenseKey: import("zod").ZodOptional<import("zod").ZodUnion<[import("zod").ZodString, import("zod").ZodRecord<import("zod").ZodString, import("zod").ZodString>, import("zod").ZodFunction<import("zod").ZodTuple<[], import("zod").ZodUnknown>, import("zod").ZodUnknown>]>>;
    customUserAgent: import("zod").ZodOptional<import("zod").ZodString>;
    devtools: import("zod").ZodOptional<import("zod").ZodUnion<[import("zod").ZodBoolean, import("zod").ZodObject<{
        user: import("zod").ZodString;
        pass: import("zod").ZodString;
    }, "strip", import("zod").ZodTypeAny, {
        user?: string;
        pass?: string;
    }, {
        user?: string;
        pass?: string;
    }>]>>;
    blockCrashLogs: import("zod").ZodDefault<import("zod").ZodBoolean>;
    cacheEnabled: import("zod").ZodDefault<import("zod").ZodBoolean>;
    browserRevision: import("zod").ZodOptional<import("zod").ZodString>;
    throwErrorOnTosBlock: import("zod").ZodOptional<import("zod").ZodBoolean>;
    headless: import("zod").ZodDefault<import("zod").ZodBoolean>;
    autoRefresh: import("zod").ZodDefault<import("zod").ZodBoolean>;
    qrRefreshS: import("zod").ZodOptional<import("zod").ZodNumber>;
    qrTimeout: import("zod").ZodDefault<import("zod").ZodNumber>;
    waitForRipeSessionTimeout: import("zod").ZodDefault<import("zod").ZodNumber>;
    executablePath: import("zod").ZodOptional<import("zod").ZodString>;
    useChrome: import("zod").ZodDefault<import("zod").ZodBoolean>;
    proxyServerCredentials: import("zod").ZodOptional<import("zod").ZodObject<{
        protocol: import("zod").ZodOptional<import("zod").ZodString>;
        address: import("zod").ZodString;
        username: import("zod").ZodString;
        password: import("zod").ZodString;
    }, "strip", import("zod").ZodTypeAny, {
        password?: string;
        protocol?: string;
        address?: string;
        username?: string;
    }, {
        password?: string;
        protocol?: string;
        address?: string;
        username?: string;
    }>>;
    qrLogSkip: import("zod").ZodDefault<import("zod").ZodBoolean>;
    restartOnCrash: import("zod").ZodOptional<import("zod").ZodAny>;
    disableSpins: import("zod").ZodDefault<import("zod").ZodBoolean>;
    logConsole: import("zod").ZodDefault<import("zod").ZodBoolean>;
    logConsoleErrors: import("zod").ZodDefault<import("zod").ZodBoolean>;
    authTimeout: import("zod").ZodDefault<import("zod").ZodNumber>;
    oorTimeout: import("zod").ZodDefault<import("zod").ZodNumber>;
    killProcessOnBrowserClose: import("zod").ZodDefault<import("zod").ZodBoolean>;
    safeMode: import("zod").ZodDefault<import("zod").ZodBoolean>;
    skipSessionSave: import("zod").ZodDefault<import("zod").ZodBoolean>;
    popup: import("zod").ZodDefault<import("zod").ZodUnion<[import("zod").ZodBoolean, import("zod").ZodNumber]>>;
    qrPopUpOnly: import("zod").ZodOptional<import("zod").ZodBoolean>;
    inDocker: import("zod").ZodDefault<import("zod").ZodBoolean>;
    qrQuality: import("zod").ZodDefault<import("zod").ZodNumber>;
    qrFormat: import("zod").ZodDefault<import("zod").ZodNativeEnum<typeof import("./config").QRFormat>>;
    hostNotificationLang: import("zod").ZodOptional<import("zod").ZodNativeEnum<typeof import("./config").NotificationLanguage>>;
    blockAssets: import("zod").ZodDefault<import("zod").ZodBoolean>;
    keepUpdated: import("zod").ZodDefault<import("zod").ZodBoolean>;
    resizable: import("zod").ZodDefault<import("zod").ZodBoolean>;
    viewport: import("zod").ZodOptional<import("zod").ZodObject<{
        width: import("zod").ZodDefault<import("zod").ZodNumber>;
        height: import("zod").ZodDefault<import("zod").ZodNumber>;
    }, "strip", import("zod").ZodTypeAny, {
        width?: number;
        height?: number;
    }, {
        width?: number;
        height?: number;
    }>>;
    legacy: import("zod").ZodDefault<import("zod").ZodBoolean>;
    deleteSessionDataOnLogout: import("zod").ZodDefault<import("zod").ZodBoolean>;
    killProcessOnTimeout: import("zod").ZodDefault<import("zod").ZodBoolean>;
    killProcessOnBan: import("zod").ZodDefault<import("zod").ZodBoolean>;
    corsFix: import("zod").ZodDefault<import("zod").ZodBoolean>;
    callTimeout: import("zod").ZodDefault<import("zod").ZodNumber>;
    screenshotOnInitializationBrowserError: import("zod").ZodDefault<import("zod").ZodBoolean>;
    eventMode: import("zod").ZodDefault<import("zod").ZodBoolean>;
    logFile: import("zod").ZodDefault<import("zod").ZodBoolean>;
    idCorrection: import("zod").ZodDefault<import("zod").ZodBoolean>;
    stickerServerEndpoint: import("zod").ZodDefault<import("zod").ZodUnion<[import("zod").ZodString, import("zod").ZodBoolean]>>;
    ghPatch: import("zod").ZodDefault<import("zod").ZodBoolean>;
    cachedPatch: import("zod").ZodDefault<import("zod").ZodBoolean>;
    logDebugInfoAsObject: import("zod").ZodDefault<import("zod").ZodBoolean>;
    logInternalEvents: import("zod").ZodOptional<import("zod").ZodBoolean>;
    killClientOnLogout: import("zod").ZodDefault<import("zod").ZodBoolean>;
    throwOnExpiredSessionData: import("zod").ZodDefault<import("zod").ZodBoolean>;
    useNativeProxy: import("zod").ZodDefault<import("zod").ZodBoolean>;
    raspi: import("zod").ZodDefault<import("zod").ZodBoolean>;
    pQueueDefault: import("zod").ZodOptional<import("zod").ZodAny>;
    messagePreprocessor: import("zod").ZodOptional<import("zod").ZodAny>;
    preprocFilter: import("zod").ZodOptional<import("zod").ZodString>;
    cloudUploadOptions: import("zod").ZodOptional<import("zod").ZodObject<{
        provider: import("zod").ZodNativeEnum<typeof import("./config").CLOUD_PROVIDERS>;
        accessKeyId: import("zod").ZodString;
        secretAccessKey: import("zod").ZodString;
        bucket: import("zod").ZodString;
        region: import("zod").ZodOptional<import("zod").ZodString>;
        ignoreHostAccount: import("zod").ZodOptional<import("zod").ZodBoolean>;
        directory: import("zod").ZodOptional<import("zod").ZodUnion<[import("zod").ZodNativeEnum<typeof import("./config").DIRECTORY_STRATEGY>, import("zod").ZodString]>>;
        public: import("zod").ZodOptional<import("zod").ZodBoolean>;
        headers: import("zod").ZodOptional<import("zod").ZodRecord<import("zod").ZodString, import("zod").ZodString>>;
    }, "strip", import("zod").ZodTypeAny, {
        provider?: import("./config").CLOUD_PROVIDERS;
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        ignoreHostAccount?: boolean;
        directory?: string;
        public?: boolean;
        headers?: Record<string, string>;
    }, {
        provider?: import("./config").CLOUD_PROVIDERS;
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        ignoreHostAccount?: boolean;
        directory?: string;
        public?: boolean;
        headers?: Record<string, string>;
    }>>;
    onError: import("zod").ZodDefault<import("zod").ZodNativeEnum<typeof import("./config").OnError>>;
    multiDevice: import("zod").ZodDefault<import("zod").ZodBoolean>;
    sessionDataBucketAuth: import("zod").ZodOptional<import("zod").ZodString>;
    autoEmoji: import("zod").ZodDefault<import("zod").ZodUnion<[import("zod").ZodString, import("zod").ZodLiteral<false>]>>;
    maxChats: import("zod").ZodOptional<import("zod").ZodNumber>;
    socketMode: import("zod").ZodDefault<import("zod").ZodBoolean>;
    apiLifecycle: import("zod").ZodDefault<import("zod").ZodEnum<["immediate", "post-connection", "hybrid"]>>;
    apiKey: import("zod").ZodOptional<import("zod").ZodString>;
    port: import("zod").ZodDefault<import("zod").ZodNumber>;
    host: import("zod").ZodDefault<import("zod").ZodString>;
    cors: import("zod").ZodDefault<import("zod").ZodUnion<[import("zod").ZodString, import("zod").ZodArray<import("zod").ZodString, "many">]>>;
    webhook: import("zod").ZodOptional<import("zod").ZodString>;
    ezqr: import("zod").ZodDefault<import("zod").ZodBoolean>;
    elasticUrl: import("zod").ZodOptional<import("zod").ZodString>;
    elasticUsername: import("zod").ZodOptional<import("zod").ZodString>;
    elasticPassword: import("zod").ZodOptional<import("zod").ZodString>;
    elasticBufferSize: import("zod").ZodDefault<import("zod").ZodNumber>;
    elasticPipeline: import("zod").ZodOptional<import("zod").ZodString>;
    elasticIndexPrefix: import("zod").ZodDefault<import("zod").ZodString>;
    s3Sync: import("zod").ZodOptional<import("zod").ZodObject<{
        bucket: import("zod").ZodString;
        region: import("zod").ZodString;
        accessKeyId: import("zod").ZodString;
        secretAccessKey: import("zod").ZodString;
        endpoint: import("zod").ZodOptional<import("zod").ZodString>;
        host: import("zod").ZodOptional<import("zod").ZodString>;
        syncInterval: import("zod").ZodDefault<import("zod").ZodNumber>;
    }, "strip", import("zod").ZodTypeAny, {
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        host?: string;
        endpoint?: string;
        syncInterval?: number;
    }, {
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        host?: string;
        endpoint?: string;
        syncInterval?: number;
    }>>;
}, "strip", import("zod").ZodTypeAny, {
    sessionData?: string | import("zod").objectOutputType<{
        WABrowserId: import("zod").ZodOptional<import("zod").ZodString>;
        WASecretBundle: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken1: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken2: import("zod").ZodOptional<import("zod").ZodString>;
    }, import("zod").ZodTypeAny, "passthrough">;
    sessionId?: string;
    linkCode?: string;
    browserWSEndpoint?: string;
    useStealth?: boolean;
    sessionDataPath?: string;
    bypassCSP?: boolean;
    chromiumArgs?: string[];
    skipBrokenMethodsCheck?: boolean;
    skipUpdateCheck?: boolean;
    licenseKey?: string | Record<string, string> | ((...args: unknown[]) => unknown);
    customUserAgent?: string;
    devtools?: boolean | {
        user?: string;
        pass?: string;
    };
    blockCrashLogs?: boolean;
    cacheEnabled?: boolean;
    browserRevision?: string;
    throwErrorOnTosBlock?: boolean;
    headless?: boolean;
    autoRefresh?: boolean;
    qrRefreshS?: number;
    qrTimeout?: number;
    waitForRipeSessionTimeout?: number;
    executablePath?: string;
    useChrome?: boolean;
    proxyServerCredentials?: {
        password?: string;
        protocol?: string;
        address?: string;
        username?: string;
    };
    qrLogSkip?: boolean;
    restartOnCrash?: any;
    disableSpins?: boolean;
    logConsole?: boolean;
    logConsoleErrors?: boolean;
    authTimeout?: number;
    oorTimeout?: number;
    killProcessOnBrowserClose?: boolean;
    safeMode?: boolean;
    skipSessionSave?: boolean;
    popup?: number | boolean;
    qrPopUpOnly?: boolean;
    inDocker?: boolean;
    qrQuality?: number;
    qrFormat?: import("./config").QRFormat;
    hostNotificationLang?: import("./config").NotificationLanguage;
    blockAssets?: boolean;
    keepUpdated?: boolean;
    resizable?: boolean;
    viewport?: {
        width?: number;
        height?: number;
    };
    legacy?: boolean;
    deleteSessionDataOnLogout?: boolean;
    killProcessOnTimeout?: boolean;
    killProcessOnBan?: boolean;
    corsFix?: boolean;
    callTimeout?: number;
    screenshotOnInitializationBrowserError?: boolean;
    eventMode?: boolean;
    logFile?: boolean;
    idCorrection?: boolean;
    stickerServerEndpoint?: string | boolean;
    ghPatch?: boolean;
    cachedPatch?: boolean;
    logDebugInfoAsObject?: boolean;
    logInternalEvents?: boolean;
    killClientOnLogout?: boolean;
    throwOnExpiredSessionData?: boolean;
    useNativeProxy?: boolean;
    raspi?: boolean;
    pQueueDefault?: any;
    messagePreprocessor?: any;
    preprocFilter?: string;
    cloudUploadOptions?: {
        provider?: import("./config").CLOUD_PROVIDERS;
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        ignoreHostAccount?: boolean;
        directory?: string;
        public?: boolean;
        headers?: Record<string, string>;
    };
    onError?: import("./config").OnError;
    multiDevice?: boolean;
    sessionDataBucketAuth?: string;
    autoEmoji?: string | false;
    maxChats?: number;
    ezqr?: boolean;
    socketMode?: boolean;
    apiLifecycle?: "immediate" | "post-connection" | "hybrid";
    apiKey?: string;
    port?: number;
    host?: string;
    cors?: string | string[];
    webhook?: string;
    elasticUrl?: string;
    elasticUsername?: string;
    elasticPassword?: string;
    elasticBufferSize?: number;
    elasticPipeline?: string;
    elasticIndexPrefix?: string;
    s3Sync?: {
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        host?: string;
        endpoint?: string;
        syncInterval?: number;
    };
}, {
    sessionData?: string | import("zod").objectInputType<{
        WABrowserId: import("zod").ZodOptional<import("zod").ZodString>;
        WASecretBundle: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken1: import("zod").ZodOptional<import("zod").ZodString>;
        WAToken2: import("zod").ZodOptional<import("zod").ZodString>;
    }, import("zod").ZodTypeAny, "passthrough">;
    sessionId?: string;
    linkCode?: string;
    browserWSEndpoint?: string;
    useStealth?: boolean;
    sessionDataPath?: string;
    bypassCSP?: boolean;
    chromiumArgs?: string[];
    skipBrokenMethodsCheck?: boolean;
    skipUpdateCheck?: boolean;
    licenseKey?: string | Record<string, string> | ((...args: unknown[]) => unknown);
    customUserAgent?: string;
    devtools?: boolean | {
        user?: string;
        pass?: string;
    };
    blockCrashLogs?: boolean;
    cacheEnabled?: boolean;
    browserRevision?: string;
    throwErrorOnTosBlock?: boolean;
    headless?: boolean;
    autoRefresh?: boolean;
    qrRefreshS?: number;
    qrTimeout?: number;
    waitForRipeSessionTimeout?: number;
    executablePath?: string;
    useChrome?: boolean;
    proxyServerCredentials?: {
        password?: string;
        protocol?: string;
        address?: string;
        username?: string;
    };
    qrLogSkip?: boolean;
    restartOnCrash?: any;
    disableSpins?: boolean;
    logConsole?: boolean;
    logConsoleErrors?: boolean;
    authTimeout?: number;
    oorTimeout?: number;
    killProcessOnBrowserClose?: boolean;
    safeMode?: boolean;
    skipSessionSave?: boolean;
    popup?: number | boolean;
    qrPopUpOnly?: boolean;
    inDocker?: boolean;
    qrQuality?: number;
    qrFormat?: import("./config").QRFormat;
    hostNotificationLang?: import("./config").NotificationLanguage;
    blockAssets?: boolean;
    keepUpdated?: boolean;
    resizable?: boolean;
    viewport?: {
        width?: number;
        height?: number;
    };
    legacy?: boolean;
    deleteSessionDataOnLogout?: boolean;
    killProcessOnTimeout?: boolean;
    killProcessOnBan?: boolean;
    corsFix?: boolean;
    callTimeout?: number;
    screenshotOnInitializationBrowserError?: boolean;
    eventMode?: boolean;
    logFile?: boolean;
    idCorrection?: boolean;
    stickerServerEndpoint?: string | boolean;
    ghPatch?: boolean;
    cachedPatch?: boolean;
    logDebugInfoAsObject?: boolean;
    logInternalEvents?: boolean;
    killClientOnLogout?: boolean;
    throwOnExpiredSessionData?: boolean;
    useNativeProxy?: boolean;
    raspi?: boolean;
    pQueueDefault?: any;
    messagePreprocessor?: any;
    preprocFilter?: string;
    cloudUploadOptions?: {
        provider?: import("./config").CLOUD_PROVIDERS;
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        ignoreHostAccount?: boolean;
        directory?: string;
        public?: boolean;
        headers?: Record<string, string>;
    };
    onError?: import("./config").OnError;
    multiDevice?: boolean;
    sessionDataBucketAuth?: string;
    autoEmoji?: string | false;
    maxChats?: number;
    ezqr?: boolean;
    socketMode?: boolean;
    apiLifecycle?: "immediate" | "post-connection" | "hybrid";
    apiKey?: string;
    port?: number;
    host?: string;
    cors?: string | string[];
    webhook?: string;
    elasticUrl?: string;
    elasticUsername?: string;
    elasticPassword?: string;
    elasticBufferSize?: number;
    elasticPipeline?: string;
    elasticIndexPrefix?: string;
    s3Sync?: {
        accessKeyId?: string;
        secretAccessKey?: string;
        bucket?: string;
        region?: string;
        host?: string;
        endpoint?: string;
        syncInterval?: number;
    };
}>;
export type ClientConfig = Config;
export declare function migrateV4Config(oldConfig: any): ClientConfig;
//# sourceMappingURL=client-config.d.ts.map