/** OpenWA-authored recipe definitions, version 1. */
export const definitions = [
 ['grayscale','⚫','Convert RGB to luminance with the shared Rust kernel.',false,{},'kernel'],
 ['stereo','👓','Separate red and blue channels with the shared Rust kernel.',false,{offset:10},'kernel'],
 ['dilate','➕','Dilate RGBA channels with the shared Rust kernel.',false,{iterations:1},'kernel'],
 ['erode','➖','Erode RGBA channels with the shared Rust kernel.',false,{iterations:1},'kernel'],
 ['bayer','▦','Expand the pixels into a Bayer colour mosaic.',false,{},'kernel'],

 ['comic','💬','Posterise colours and draw dark Sobel outlines.',false,{levels:5},'edges'],
 ['earth','🌍','Wrap the input onto a shaded sphere and rotate it.',true,{turns:1},'warp'],
 ['edge','✏️','Draw white Sobel luminance edges on black.',false,{strength:2},'edges'],
 ['emboss','🗿','Apply a directional relief kernel with a grey bias.',false,{strength:1.5},'pixels'],
 ['fisheye','🐟','Magnify the centre using a radial barrel lens.',false,{strength:0.65},'warp'],
 ['flash','⚡','Pulse a white flash over the image.',true,{strength:0.9},'canvas'],
 ['freeze','🧊','Keep the first decoded frame of an animation.',false,{},'timing'],
 ['gold','🥇','Map luminance to a dark-brown → gold → cream gradient.',false,{},'pixels'],
 ['half','◐','Invert the right half while keeping the left half unchanged.',false,{},'pixels'],
 ['invert','🙃','Invert RGB channels while preserving transparency.',false,{},'pixels'],
 ['jail','🔒','Overlay steel prison bars and a small lock.',false,{bars:5},'canvas'],
 ['kaleidoscope','🔮','Reflect the source across six angular sectors.',false,{sectors:6},'warp'],
 ['leak','🌅','Screen-blend a warm radial light leak.',false,{strength:0.75},'canvas'],
 ['lego','🧱','Average a brick grid, then draw raised circular studs.',false,{cell:32},'tiles'],
 ['liquid','💧','Animate horizontal and vertical sine-wave refraction.',true,{strength:18},'warp'],
 ['low','📉','Reduce to 64px, compress as low-quality JPEG, then enlarge.',false,{size:64,quality:0.08},'canvas'],
 ['magik','🪄','Remove low-energy seams in both axes, then stretch back.',false,{workingSize:192,retain:0.72},'seam'],
 ['mirror','🪞','Flip the image horizontally.',false,{},'canvas'],
 ['mosaic','🟪','Replace each 24px cell with its average RGBA colour.',false,{cell:24},'tiles'],
 ['motion','💨','Blend shifted copies into a directional motion blur.',false,{distance:28,samples:9},'canvas'],
 ['newspaper','📰','Place a halftone greyscale image in a newspaper layout.',false,{headline:'STICKER DAILY'},'canvas'],
 ['opaque','⬜','Composite transparency onto the chosen solid background.',false,{color:'#ffffff'},'canvas'],
 ['pixelate','👾','Downsample to a 32px grid and enlarge with nearest neighbours.',false,{size:32},'canvas'],
 ['polaroid','📸','Fit the input inside a white instant-photo frame.',false,{caption:'OpenWA'},'canvas'],
 ['rainbow','🌈','Animate a rainbow gradient using a colour blend.',true,{strength:0.65},'canvas'],
 ['random','🎲','Select one reproducible effect from a safe pool using a seed.',false,{seed:42},'seed'],
 ['recede','🔭','Animate the image shrinking into the distance.',true,{minimum:0.18},'canvas'],
 ['resize','📐','Resize to fit inside 300 × 300px on the 512px output.',false,{width:300,height:300},'canvas'],
 ['scramble','🧩','Shuffle a 4 × 4 tile grid with a reproducible seed.',false,{grid:4,seed:42},'tiles'],
 ['screen','📺','Add CRT scanlines, a cyan cast and dark rounded corners.',false,{},'canvas'],
 ['shake','🫨','Shake the whole image with irregular looping offsets.',true,{distance:18},'canvas'],
 ['sketch','🖊️','Draw dark pencil-like edges on off-white paper.',false,{strength:2.4},'edges'],
 ['slow','🐌','Multiply decoded animation frame durations by three.',false,{factor:3},'timing'],
 ['smooth','🫧','Apply a soft 3px browser blur.',false,{radius:3},'canvas'],
 ['snap','🫰','Dissolve the image into drifting, fading square particles.',true,{cell:24,seed:42},'tiles'],
 ['solar','☀️','Solarise channels above a brightness threshold.',false,{threshold:128},'pixels'],
 ['sort','📊','Sort visible horizontal runs by luminance, keeping alpha gaps.',false,{},'sort'],
 ['sparkle','✨','Pulse small four-point sparkles over the input.',true,{count:18,seed:42},'canvas'],
 ['spiral','🌀','Twist angles by radius to form a spiral warp.',false,{strength:3.8},'warp'],
 ['spread','🎇','Animate grid tiles scattering radially from the centre.',true,{cell:48,strength:0.9},'tiles'],
 ['square','🔲','Crop a centred 384px square and upscale it to 512px.',false,{size:384},'canvas'],
 ['squish','🥞','Animate bottom-anchored vertical compression.',true,{minimum:0.35},'canvas'],
 ['stack','🗂️','Compose three offset, slightly rotated copies.',false,{copies:3},'canvas'],
 ['stamp','📮','Create a two-tone ink image with a perforated stamp border.',false,{color:'#a73242'},'canvas'],
 ['stars','⭐','Clip the image to a five-point star.',false,{},'canvas'],
 ['stripes','🦓','Cut transparent diagonal stripes through the image.',false,{width:32},'canvas'],
 ['swirl','🌪️','Twist the centre while leaving the outside nearly unchanged.',false,{strength:3},'warp'],
 ['tint','🎨','Blend a chosen colour tint over the input.',false,{color:'#e056ae',strength:0.45},'canvas'],
 ['trace','📎','Overlay sharp dark contours on a pale greyscale image.',false,{strength:2},'edges'],
 ['triangle','🔺','Average each half-cell into coloured triangular facets.',false,{cell:40},'tiles'],
 ['trip','🍄','Animate sine refraction with cycling RGB channel phases.',true,{strength:12},'warp'],
 ['uncanny','😶','Make an eerie high-contrast greyscale portrait with a vignette.',false,{},'pixels'],
 ['unfreeze','🔥','Animate a still with a subtle pan and zoom; lost motion is not recovered.',true,{zoom:0.12},'canvas'],
 ['unsharpen','🔍','Use an unsharp mask to sharpen detail (chosen meaning of this ambiguous name).',false,{amount:1.4,radius:2},'pixels'],
 ['vaporwave','🌆','Combine cyan/magenta duotone, scanlines and a neon frame.',false,{},'canvas'],
 ['vibrate','📳','Alternate small horizontal offsets rapidly.',true,{distance:6},'canvas'],
 ['woke','👁️','Add glowing laser beams at two configurable eye anchors.',false,{eyes:[[0.38,0.40],[0.62,0.40]],color:'#ff2449'},'canvas']
];
export const recipes = Object.fromEntries(definitions.map(([name,emoji,description,animated,defaults,referenceGroup])=>[name,{name,emoji,description,animated,defaults,referenceGroup}]));
