"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleListener = void 0;
var SimpleListener;
(function (SimpleListener) {
    SimpleListener["Message"] = "onMessage";
    SimpleListener["AnyMessage"] = "onAnyMessage";
    SimpleListener["MessageDeleted"] = "onMessageDeleted";
    SimpleListener["Ack"] = "onAck";
    SimpleListener["AddedToGroup"] = "onAddedToGroup";
    SimpleListener["ChatDeleted"] = "onChatDeleted";
    SimpleListener["Battery"] = "onBattery";
    SimpleListener["ChatOpened"] = "onChatOpened";
    SimpleListener["IncomingCall"] = "onIncomingCall";
    SimpleListener["CallState"] = "onCallState";
    SimpleListener["GlobalParticipantsChanged"] = "onGlobalParticipantsChanged";
    SimpleListener["GroupApprovalRequest"] = "onGroupApprovalRequest";
    SimpleListener["ChatState"] = "onChatState";
    SimpleListener["Logout"] = "onLogout";
    SimpleListener["Plugged"] = "onPlugged";
    SimpleListener["StateChanged"] = "onStateChanged";
    SimpleListener["Button"] = "onButton";
    SimpleListener["PollVote"] = "onPollVote";
    SimpleListener["Broadcast"] = "onBroadcast";
    SimpleListener["Label"] = "onLabel";
    SimpleListener["Story"] = "onStory";
    SimpleListener["RemovedFromGroup"] = "onRemovedFromGroup";
    SimpleListener["ContactAdded"] = "onContactAdded";
    SimpleListener["Order"] = "onOrder";
    SimpleListener["NewProduct"] = "onNewProduct";
    SimpleListener["Reaction"] = "onReaction";
    SimpleListener["GroupChange"] = "onGroupChange";
})(SimpleListener || (exports.SimpleListener = SimpleListener = {}));
//# sourceMappingURL=events.js.map