// This file is auto-generated by packages/schema/scripts/gen-client-reference-docs.ts

// Do not edit this file directly.



export interface AddLabelParams {
  /**
   * Label ID or name
   */
  label: string;
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  chatId: string;
}

export interface AddParticipantParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface ApproveGroupJoinRequestParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface ArchiveChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface BlockContactParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface CheckNumberStatusParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface CheckReadReceiptsParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface ClearChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface CreateGroupParams {
  /**
   * Group name
   */
  name: string;
  /**
   * Contact IDs to add A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contacts: string[];
}

export interface DecryptMediaParams {
  /**
   * Message object containing media
   */
  message: { ack: any; author: any; body: any; broadcast: any; caption: any; chat: any; chatId: any; clientUrl: any; content: any; deprecatedMms3Url: any; from: any; fromMe: any; id: any; invis: any; isForwarded: any; isGroupMsg: any; isMedia: any; isMMS: any; isNewMsg: any; isNotification: any; isPSA: any; isQuotedMsgAvailable: any; labels: any; mentionedJidList: any; notifyName: any; quotedMsg: any; quotedMsgObj: any; recvFresh: any; self: any; sender: any; senderId: any; star: any; t: any; timestamp: any; to: any; type: any; };
}

export interface DeleteChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface DeleteMessageParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
  /**
   * Message ID(s) to process Branded type: MessageId[]
   * @example ["false_447123456789@c.us_ABC123","false_447123456789@c.us_DEF456"]
   * @remarks Key aliases: 'messages'
   */
  messageId: string[] | string;
  /**
   * Delete only locally
   */
  onlyLocal: boolean;
}

export interface DeleteStatusParams {
  /**
   * Status ID(s)
   */
  statusesToDelete: string | string[];
}

export interface DemoteParticipantParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface DownloadMediaParams {
  /**
   * Message object containing media
   */
  message: { ack: any; author: any; body: any; broadcast: any; caption: any; chat: any; chatId: any; clientUrl: any; content: any; deprecatedMms3Url: any; from: any; fromMe: any; id: any; invis: any; isForwarded: any; isGroupMsg: any; isMedia: any; isMMS: any; isNewMsg: any; isNotification: any; isPSA: any; isQuotedMsgAvailable: any; labels: any; mentionedJidList: any; notifyName: any; quotedMsg: any; quotedMsgObj: any; recvFresh: any; self: any; sender: any; senderId: any; star: any; t: any; timestamp: any; to: any; type: any; };
  /**
   * File path to save the media
   */
  path: string;
}

export interface ForwardMessagesParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message ID(s) to process Branded type: MessageId[]
   * @example ["false_447123456789@c.us_ABC123","false_447123456789@c.us_DEF456"]
   * @remarks Key aliases: 'messages'
   */
  messages: string[] | string;
  /**
   * Skip own messages
   * @example false
   */
  skipMyMessages: boolean;
}

export interface GetAllChatsParams {
  /**
   * Only chats with unread messages
   * @example false
   */
  withNewMessagesOnly: boolean;
}

export interface GetAllGroupsParams {
  /**
   * Only chats with unread messages
   * @example false
   */
  withNewMessagesOnly: boolean;
}

export interface GetAllMessagesParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId?: string;
  /**
   * Include own messages
   */
  includeMe: boolean;
  /**
   * Include notification messages
   */
  includeNotifications: boolean;
}

export interface GetBusinessProductsParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetBusinessProfileParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface GetChatsByLabelParams {
  /**
   * Label name
   */
  label: string;
}

export interface GetCommonGroupsParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetCommunityAdminIdsParams {
  /**
   * Community ID A WhatsApp community JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   */
  communityId: string;
}

export interface GetCommunityAdminsParams {
  /**
   * Community ID A WhatsApp community JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   */
  communityId: string;
}

export interface GetCommunityInfoParams {
  /**
   * Community ID A WhatsApp community JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   */
  communityId: string;
}

export interface GetCommunityParticipantIdsParams {
  /**
   * Community ID A WhatsApp community JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   */
  communityId: string;
}

export interface GetCommunityParticipantsParams {
  /**
   * Community ID A WhatsApp community JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   */
  communityId: string;
}

export interface GetContactParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetGroupAdminsParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface GetGroupInfoParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface GetGroupInviteLinkParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface GetGroupMembersParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface GetGroupMembersIdParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface GetMessageByIdParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
}

export interface GetMessageInfoParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
}

export interface GetMessagesForLLMParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
  last: number;
}

export interface GetMyLastMessageParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId?: string;
}

export interface GetNumberProfileParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetOrderParams {
  /**
   * Order or message ID
   */
  id: string;
}

export interface GetProfilePictureParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface GetSnapshotParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId?: string;
  width?: number;
  height?: number;
}

export interface GetStarredMessagesParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId?: string;
}

export interface GetStatusParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface GetUserAgentParams {
  /**
   * User agent string
   * @example "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
   * @remarks Key aliases: 'userA'
   * @remarks Deprecated key aliases: 'userA'
   */
  userAgent?: string;
}

export interface GetVCardsParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
}

export interface IsChatOnlineParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface JoinGroupViaLinkParams {
  /**
   * Group invite link
   */
  link: string;
  /**
   * Return chat object
   */
  returnChatObj?: boolean;
}

export interface LeaveGroupParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface LoadEarlierMessagesParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
  /**
   * Number of messages to load (default: 20)
   */
  count?: number;
  /**
   * Whether to include messages from the host account (default: false)
   */
  includeMe?: boolean;
}

export interface MarkAsReadParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface MarkAsUnreadParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface MuteChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
  /**
   * Mute duration
   */
  muteDuration: number | string;
}

export interface PinChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface PostImageStatusParams {
  /**
   * Image data URL
   */
  image: string;
  /**
   * Status caption
   */
  caption?: string;
}

export interface PostTextStatusParams {
  /**
   * Status text
   */
  text: string;
  /**
   * Background color
   */
  backgroundColor?: string;
  /**
   * Font style
   */
  font?: number;
}

export interface PostVideoStatusParams {
  /**
   * Video data URL
   */
  video: string;
  /**
   * Status caption
   */
  caption?: string;
}

export interface PromoteParticipantParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface ReactParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
  /**
   * Emoji reaction
   */
  emoji: string;
}

export interface RejectGroupJoinRequestParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface RemoveLabelParams {
  /**
   * Label ID or name
   */
  label: string;
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  chatId: string;
}

export interface RemoveParticipantParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface RevokeGroupInviteLinkParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
}

export interface SendAdvancedButtonsParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message body, location, or media
   */
  body: string | unknown;
  /**
   * Array of advanced buttons (max 3)
   */
  buttons: unknown[];
  /**
   * Message text
   */
  text: string;
  /**
   * Message footer
   */
  footer: string;
  /**
   * Filename if body is a file
   */
  filename: string;
}

export interface SendAudioParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Audio file (path, URL, DataURL, or Base64) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:audio/mpeg;base64,SUQzBAAAAAAAI1RTU0UAAAA..."
   */
  file: string;
  /**
   * Filename with extension
   * @example "document.pdf"
   */
  filename?: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
}

export interface SendBannerParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Base64 encoded JPEG
   */
  base64: string;
}

export interface SendButtonsParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message body or location
   */
  body: string | unknown;
  /**
   * Array of buttons (max 3)
   */
  buttons: unknown[];
  /**
   * Message title
   */
  title?: string;
  /**
   * Message footer
   */
  footer?: string;
}

export interface SendContactParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  contactId: string | string[];
}

export interface SendFileParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * File (path, URL, DataURL, Base64, or Buffer) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:application/pdf;base64,JVBERi0xLjQK..."
   */
  file: string;
  /**
   * Filename with extension
   * @example "document.pdf"
   */
  filename?: string;
  /**
   * Media caption
   * @example "Check out this image!"
   */
  caption?: string;
}

export interface SendFileFromUrlParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * URL of the file to download
   */
  url: string;
  /**
   * Filename for the sent file
   */
  filename: string;
  /**
   * Caption for the file
   */
  caption?: string;
  /**
   * HTTP headers for the download request
   */
  headers?: Record<string, any>;
}

export interface SendImageParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Image file (path, URL, DataURL, or Base64) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:image/png;base64,iVBORw0KGgo..."
   */
  imgData: string;
  /**
   * Filename with extension
   * @example "document.pdf"
   */
  filename?: string;
  /**
   * Media caption
   * @example "Check out this image!"
   */
  caption?: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  id?: string;
  /**
   * Wait for message ID
   * @example true
   */
  waitForId: boolean;
}

export interface SendLinkWithAutoPreviewParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Link URL
   */
  url: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  text?: string;
  /**
   * Base64 thumbnail override
   */
  thumbnail?: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
  /**
   * Custom thumbnail size
   */
  customSize?: { height: any; width: any; };
}

export interface SendListMessageParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * List sections
   */
  sections: unknown[];
  /**
   * List title
   */
  title: string;
  /**
   * List description
   */
  description: string;
  /**
   * Action button text
   */
  actionText: string;
}

export interface SendLocationParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Latitude coordinate
   * @example 51.5074
   */
  lat: number | string;
  /**
   * Longitude coordinate
   * @example -0.1278
   */
  lng: number | string;
  /**
   * Location name or description
   * @example "London, UK"
   */
  loc?: string;
  /**
   * Address text
   */
  address?: string;
  /**
   * Address link
   */
  url?: string;
}

export interface SendMessageWithThumbParams {
  /**
   * Base64 thumbnail (max 200x200px)
   */
  thumb: string;
  /**
   * Link URL
   */
  url: string;
  /**
   * Link title
   */
  title: string;
  /**
   * Link description
   */
  description: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  content: string;
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
  /**
   * Custom thumbnail size
   */
  customSize?: { height: any; width: any; };
}

export interface SendMultipleContactsParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactIds: string[];
}

export interface SendPaymentRequestParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Amount in 1000 format (e.g £10 => 10000)
   */
  amount: number;
  /**
   * 3 letter currency code
   */
  currency: string;
  /**
   * Optional message
   */
  message?: string;
}

export interface SendPollParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Poll question
   */
  name: string;
  /**
   * Poll options (2-12)
   */
  options: string[];
  /**
   * Number of selectable options
   */
  selectableCount: number;
}

export interface SendPttParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Audio file (path, URL, DataURL, or Base64) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:audio/mpeg;base64,SUQzBAAAAAAAI1RTU0UAAAA..."
   */
  file: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
}

export interface SendReplyWithMentionsParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  content: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  replyMessageId: string;
  /**
   * Removes all tags within the message
   */
  hideTags?: boolean;
  /**
   * List of mentioned contact IDs
   * @example ["447123456789@c.us","441234567890@c.us"]
   */
  mentions?: string[];
}

export interface SendSeenParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface SendTextParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  content: string;
  /**
   * Additional message options
   * @example &#123;"quotedMsg":"messageId","mentionedJidList":["447123456789@c.us"]&#125;
   */
  options?: any;
}

export interface SendTextWithMentionsParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  content: string;
  /**
   * Removes all tags within the message
   */
  hideTags?: boolean;
  /**
   * List of mentioned contact IDs
   * @example ["447123456789@c.us","441234567890@c.us"]
   */
  mentions?: string[];
}

export interface SendVCardParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * vCard string
   */
  vcard: string;
  /**
   * Contact display name
   */
  contactName?: string;
  /**
   * Contact number with country code
   */
  contactNumber?: string;
}

export interface SendVideoAsGifParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * Video file (path, URL, DataURL, or Base64) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:video/mp4;base64,AAAAIGZ0eXBpc29tAAACAGlzb21..."
   */
  file: string;
  /**
   * Filename with extension
   * @example "document.pdf"
   */
  filename?: string;
  /**
   * Media caption
   * @example "Check out this image!"
   */
  caption?: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
}

export interface SendYouTubeLinkParams {
  /**
   * Recipient chat ID The target chat for a send operation Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'chatId'
   */
  to: string;
  /**
   * YouTube URL
   */
  url: string;
  /**
   * Message content Branded type: Content
   * @example "Hello, world!"
   * @remarks Key aliases: 'body', 'message', 'text'
   */
  text: string;
  /**
   * Base64 thumbnail override
   */
  thumbnail?: string;
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  quotedMsgId?: string;
  /**
   * Custom thumbnail size
   */
  customSize?: { height: any; width: any; };
}

export interface SetChatEphemeralParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
  /**
   * Ephemeral setting
   */
  ephemeral: boolean | number;
}

export interface SetGroupDescriptionParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * New group description
   */
  description: string;
}

export interface SetGroupEditToAdminsOnlyParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Admins only setting
   */
  onlyAdmins: boolean;
}

export interface SetGroupIconParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Image data URL
   */
  image: string;
}

export interface SetGroupTitleParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * New group title
   */
  title: string;
}

export interface SetGroupToAdminsOnlyParams {
  /**
   * Group chat ID A WhatsApp group JID Branded type: GroupChatId Pattern: ^\d+(-\d+)?@g\.us$
   * @example "447123456789-1445627445@g.us"
   * @remarks Key aliases: 'chatId', 'groupChatId'
   * @remarks Deprecated key aliases: 'groupChatId'
   */
  groupId: string;
  /**
   * Admins only setting
   */
  onlyAdmins: boolean;
}

export interface SetMyNameParams {
  /**
   * Display name
   * @example "OpenWA Bot"
   * @remarks Key aliases: 'newName'
   * @remarks Deprecated key aliases: 'newName'
   */
  name: string;
}

export interface SetMyStatusParams {
  /**
   * Status text
   * @example "Available"
   * @remarks Key aliases: 'newStatus'
   * @remarks Deprecated key aliases: 'newStatus'
   */
  statusText: string;
}

export interface SetProfilePictureParams {
  /**
   * Image file (path, URL, DataURL, or Base64) Branded type: DataURL Pattern: ^data:.+;base64,.+$
   * @example "data:image/png;base64,iVBORw0KGgo..."
   */
  image: string;
}

export interface StarMessageParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
}

export interface UnarchiveChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface UnblockContactParams {
  /**
   * Contact ID A WhatsApp contact JID Branded type: ContactId Pattern: ^\d+@c\.us$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'id'
   */
  contactId: string;
}

export interface UnmuteChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface UnpinChatParams {
  /**
   * Chat ID (phone number or formatted ID) A contact ID, group ID, or LID JID Branded type: ChatId Pattern: ^\d+(-\d+)?@(c|g)\.us$|^\d+@lid$
   * @example "447123456789@c.us"
   * @remarks Key aliases: 'contactId', 'id'
   */
  chatId: string;
}

export interface UnstarMessageParams {
  /**
   * Message ID A WhatsApp message identifier Branded type: MessageId Pattern: ^(true|false)_.+_.+$
   * @example "false_447123456789@c.us_9C4D0965EA5C09D591334AB6BDB07FEB"
   * @remarks Key aliases: 'id', 'msgId'
   * @remarks Deprecated key aliases: 'msgId'
   */
  messageId: string;
}
