import fs from 'fs';
import path from 'path';
import { clientRegistry } from '../src/registry';

// Import methods to trigger registration side-effects
import '../src/methods';

console.log('Loading schemas and generating client...');

const generatedDir = path.join(__dirname, '../src/generated');
if (!fs.existsSync(generatedDir)) {
  fs.mkdirSync(generatedDir, { recursive: true });
}

let output = `/* eslint-disable */
/**
 * This file was automatically generated by packages/schema/scripts/gen-client-implementation.ts
 * Do not edit this file manually.
 */
import { implementMethod } from '../implementor';
import * as Methods from '../methods';

export abstract class BaseClient {
  /**
   * Execute a method via the legacy bridge
   */
  protected abstract execute(method: string, args: any): Promise<any>;

  /**
   * Bridge for V2 implementMethod fallback
   * This bridges the new 'pup' call style to the legacy 'execute' style
   */
  protected async pup(_func: any, args: any): Promise<any> {
    // Determine method name from the metadata in the registry
    // This is a bit of a hack for the generated base class
    return this.execute('unknown', args);
  }

`;

// Generate V2 Methods
const methods = clientRegistry.getAll();
methods.forEach((def) => {
  const name = def.meta.functionName;

  output += `
  /**
    * ${def.meta.description || name}
    */
  public ${name} = implementMethod(Methods.${name});
`;
});

output += `}
`;

fs.writeFileSync(path.join(generatedDir, 'BaseClient.ts'), output);
fs.writeFileSync(
  path.join(generatedDir, 'index.ts'),
  `/* eslint-disable */\nexport * from './BaseClient';\nexport * from './types';\n`
);
console.log('Successfully generated BaseClient.ts');
