import { printNode, zodToTs } from 'zod-to-ts';
import fs from 'fs';
import path from 'path';
import { Registry } from '../src/registry';
import '../src/methods'; // Ensure methods are registered

// Create generated directory
const generatedDir = path.join(__dirname, '../generated');
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}

let output = `/* eslint-disable */
/**
 * This file was automatically generated by packages/schema/scripts/gen-types.ts
 * Do not edit this file manually.
 */
`;

// Generate types for all methods
const methods = Registry.getAllMethods();

methods.forEach((method) => {
    const inputIdentifier = `${capitalize(method.name)}Input`;
    const { node: inputNode } = zodToTs(method.inputSchema as any, inputIdentifier);
    const inputType = printNode(inputNode);

    const outputIdentifier = `${capitalize(method.name)}Output`;
    const { node: outputNode } = zodToTs(method.outputSchema as any, outputIdentifier);
    const outputType = printNode(outputNode);

    output += `
export type ${inputIdentifier} = ${inputType};
export type ${outputIdentifier} = ${outputType};
`;
});

// Write types.ts
fs.writeFileSync(path.join(generatedDir, 'types.ts'), output);
console.log('Successfully generated types.ts');

function capitalize(s: string) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
