import fs from 'fs';
import path from 'path';
import { Registry, clientRegistry } from '../src/registry';

// Import methods to trigger registration side-effects
import '../src/methods';

console.log('Loading schemas and generating client...');

const generatedDir = path.join(__dirname, '../src/generated');
if (!fs.existsSync(generatedDir)) {
  fs.mkdirSync(generatedDir, { recursive: true });
}

let output = `/* eslint-disable */
/**
 * This file was automatically generated by packages/schema/scripts/gen-client-implementation.ts
 * Do not edit this file manually.
 */
import { z } from 'zod';
import * as Types from './types';
import { Registry, clientRegistry } from '../registry';
import { implementMethod } from '../implementor';
import * as Methods from '../methods';

export abstract class BaseClient {
  /**
   * Execute a method via the legacy bridge
   */
  protected abstract execute(method: string, args: any): Promise<any>;

  /**
   * Bridge for V2 implementMethod fallback
   * This bridges the new 'pup' call style to the legacy 'execute' style
   */
  protected async pup(func: any, args: any): Promise<any> {
    // Determine method name from the metadata in the registry
    // This is a bit of a hack for the generated base class
    return this.execute('unknown', args);
  }

`;

// 2. Generate V2 Methods
const v2Methods = clientRegistry.getAll();
const v2MethodNames = new Set(v2Methods.map(([_schema, meta]) => meta.functionName!));

// 1. Generate Legacy Methods (only if no V2 version exists)
const legacyMethods = Registry.getAllMethods();
legacyMethods.forEach((method) => {
  if (v2MethodNames.has(method.name)) {
    console.log(`Skipping legacy ${method.name} because V2 version exists`);
    return;
  }
  const inputType = `Types.${capitalize(method.name)}Input`;
  const outputType = `Types.${capitalize(method.name)}Output`;

  output += `
  /**
   * ${method.metadata.description} (Legacy)
   * @param args - ${inputType}
   */
  async ${method.name}(args: ${inputType}): Promise<${outputType}> {
    const methodDef = Registry.getMethod('${method.name}');
    if (!methodDef) throw new Error('Method ${method.name} not found in registry');
    
    // Validate input
    const validatedArgs = methodDef.inputSchema.parse(args);
    
    // Execute
    const result = await this.execute('${method.name}', validatedArgs);
    
    // Validate output
    return methodDef.outputSchema.parse(result);
  }
`;
});

v2Methods.forEach(([_schema, meta]) => {
  const name = meta.functionName!;

  output += `
  /**
    * ${meta.description || 'V2 Method'}
    */
  public ${name} = implementMethod(Methods.${name}V2);
`;
});

output += `}
`;

fs.writeFileSync(path.join(generatedDir, 'BaseClient.ts'), output);
console.log('Successfully generated BaseClient.ts');

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
