import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { getHttpMethodDefinitions, type HttpMethodDefinition } from '../src/http-manifest';
import { clientRegistry, getParameterMetadata, type MethodDefinition, type ParameterMetadata } from '../src/registry';

import '../src/methods';

type JsonSchema = {
  type?: string | string[];
  description?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  enum?: Array<string | number | boolean | null>;
  const?: string | number | boolean | null;
  format?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  additionalProperties?: boolean | JsonSchema;
};

type ParameterRow = {
  name: string;
  type: string;
  required: boolean;
  description: string;
  aliases: string[];
  deprecatedAliases: string[];
  example: string;
};

const generatorPath = 'packages/schema/scripts/gen-client-reference-docs.ts';
const docsDir = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../../../apps/docs/content/docs/reference/client');

function sortStrings(values: string[]): string[] {
  return [...values].sort((left, right) => left.localeCompare(right));
}

function uniqueStrings(values: Array<string | undefined>): string[] {
  return Array.from(new Set(values.filter((value): value is string => Boolean(value))));
}

function schemaToJsonSchema(schema: z.ZodTypeAny): JsonSchema {
  const serializableSchema = schema as z.ZodTypeAny & {
    toJSONSchema?: (params?: { target?: string }) => unknown;
  };

  if (typeof serializableSchema.toJSONSchema !== 'function') {
    return {};
  }

  return serializableSchema.toJSONSchema({ target: 'openapi-3.0' }) as JsonSchema;
}

function getInputShape(def: MethodDefinition): Record<string, z.ZodTypeAny> {
  return def.meta.inputSchema.shape as Record<string, z.ZodTypeAny>;
}

function stringifyExample(value: ParameterMetadata['example'] | undefined): string {
  if (value === undefined) {
    return '-';
  }

  return `\`${escapeMarkdownInline(JSON.stringify(value))}\``;
}

function escapeMarkdownInline(value: string): string {
  return value.replace(/`/g, '\\`').replace(/\|/g, '\\|').replace(/{/g, '&#123;').replace(/}/g, '&#125;');
}

function escapeTableCell(value: string): string {
  return escapeMarkdownInline(value.replace(/\n/g, ' '));
}

function escapeMdxText(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function formatList(values: string[]): string {
  return values.length > 0 ? values.map((value) => `\`${escapeMarkdownInline(value)}\``).join(', ') : '-';
}

function titleCase(value: string): string {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function pascalCase(value: string): string {
  if (!value) return '';
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function buildAllParamsInterfaces(methods: MethodDefinition[]): string {
  const interfaces = methods.map((def) => {
    const rows = buildParameterRows(def);
    if (rows.length === 0) {
      return '';
    }

    const interfaceName = pascalCase(def.meta.functionName) + 'Params';
    const fields = rows.map((row) => {
      const docParts = [];
      if (row.description) {
        docParts.push(row.description.replace(/\*\//g, '*\\/'));
      }
      if (row.example && row.example !== '-') {
        const exampleCleaned = row.example.replace(/^`|`$/g, '').replace(/\\/g, '');
        docParts.push(`@example ${exampleCleaned.replace(/\*\//g, '*\\/')}`);
      }
      if (row.aliases.length > 0) {
        docParts.push(`@remarks Key aliases: ${row.aliases.map((a) => `'${a}'`).join(', ')}`);
      }
      if (row.deprecatedAliases.length > 0) {
        docParts.push(`@remarks Deprecated key aliases: ${row.deprecatedAliases.map((a) => `'${a}'`).join(', ')}`);
      }

      const docComment = docParts.length > 0
        ? `  /**\n   * ${docParts.map((part) => part.split('\n').join('\n   * ')).join('\n   * ')}\n   */\n`
        : '';

      const name = row.name;
      const optionalSign = row.required ? '' : '?';
      const tsType = cleanTsType(row.type);
      
      return `${docComment}  ${name}${optionalSign}: ${tsType};`;
    });

    return [
      `export interface ${interfaceName} {`,
      ...fields,
      `}`
    ].join('\n');
  }).filter(Boolean);

  return [
    '// This file is auto-generated by packages/schema/scripts/gen-client-reference-docs.ts',
    '// Do not edit this file directly.',
    '',
    ...interfaces
  ].join('\n\n') + '\n';
}

function summarizeSchema(schema: JsonSchema): string {
  if (schema.const !== undefined) {
    return JSON.stringify(schema.const);
  }

  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
  }

  const compound = schema.anyOf ?? schema.oneOf;
  if (compound && compound.length > 0) {
    return uniqueStrings(compound.map(summarizeSchema)).join(' | ');
  }

  if (schema.allOf && schema.allOf.length > 0) {
    return uniqueStrings(schema.allOf.map(summarizeSchema)).join(' & ');
  }

  if (Array.isArray(schema.type)) {
    return schema.type.join(' | ');
  }

  if (schema.type === 'array') {
    return `${schema.items ? summarizeSchema(schema.items) : 'unknown'}[]`;
  }

  if (schema.type === 'object') {
    const propertyNames = schema.properties ? Object.keys(schema.properties) : [];
    if (propertyNames.length === 0) {
      return 'object';
    }

    return `object { ${sortStrings(propertyNames).join(', ')} }`;
  }

  return schema.type ?? 'unknown';
}

function buildParameterRows(def: MethodDefinition): ParameterRow[] {
  const inputSchema = schemaToJsonSchema(def.meta.inputSchema);
  const properties = inputSchema.properties ?? {};
  const required = new Set(inputSchema.required ?? []);
  const inputShape = getInputShape(def);
  const orderedNames = uniqueStrings([
    ...def.meta.parameterOrder,
    ...sortStrings(Object.keys(properties).filter((name) => !def.meta.parameterOrder.includes(name))),
  ]);

  return orderedNames.map((name) => {
    const property = properties[name] ?? {};
    const metadata = inputShape[name] ? getParameterMetadata(inputShape[name]) : undefined;
    const descriptionParts = uniqueStrings([
      property.description,
      metadata?.formatDescription,
      metadata?.brandedType ? `Branded type: ${metadata.brandedType}` : undefined,
      metadata?.pattern ? `Pattern: ${metadata.pattern}` : property.pattern ? `Pattern: ${property.pattern}` : undefined,
    ]);

    return {
      name,
      type: summarizeSchema(property),
      required: required.has(name),
      description: descriptionParts.join(' '),
      aliases: sortStrings(metadata?.keyAliases ?? []),
      deprecatedAliases: sortStrings(metadata?.deprecatedKeyAliases ?? []),
      example: stringifyExample(metadata?.example),
    };
  });
}
function cleanTsType(typeStr: string): string {
  let cleaned = typeStr.trim();
  if (cleaned === 'unknown' || !cleaned) {
    return 'any';
  }
  if (cleaned.startsWith('object {')) {
    const inner = cleaned.substring('object {'.length, cleaned.length - 1).trim();
    if (inner) {
      const parts = inner.split(',').map((p) => p.trim());
      return `{ ${parts.map((p) => `${p}: any;`).join(' ')} }`;
    }
    return 'Record<string, any>';
  }
  if (cleaned === 'object') {
    return 'Record<string, any>';
  }
  return cleaned;
}

function buildParameterTable(def: MethodDefinition, rows: ParameterRow[]): string {
  if (rows.length === 0) {
    return 'This method does not define input parameters.';
  }

  const interfaceName = pascalCase(def.meta.functionName) + 'Params';
  return `<AutoTypeTable path="./generated-method-params.ts" name="${interfaceName}" />`;
}

function buildGeneratedWarning(): string {
  return `> Generated file warning: this page is generated by \`${generatorPath}\`. Do not edit generated method content by hand.`;
}

function buildFrontmatter(title: string, description: string, icon?: string): string {
  const lines = [
    '---',
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(description)}`,
  ];

  if (icon) {
    lines.push(`icon: ${JSON.stringify(icon)}`);
  }

  lines.push('---');
  return lines.join('\n');
}

function buildRouteBlock(route: HttpMethodDefinition | undefined): string {
  if (!route) {
    return [
      '### Routes',
      '',
      '| Type | Method | Path | Name | Status |',
      '| --- | --- | --- | --- | --- |',
      '| Primary | - | - | - | Not registered |',
    ].join('\n');
  }

  const aliasRows = route.aliasRoutes
    .filter((aliasRoute) => aliasRoute.path !== route.path)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((aliasRoute) => [
      aliasRoute.deprecated ? 'Deprecated alias' : 'Alias',
      `\`${escapeTableCell(route.httpMethod)}\``,
      `\`${escapeTableCell(aliasRoute.path)}\``,
      `\`${escapeTableCell(aliasRoute.name)}\``,
      aliasRoute.deprecated ? '**Deprecated**' : 'Active',
    ]);

  const rows = [
    ['Primary', `\`${escapeTableCell(route.httpMethod)}\``, `\`${escapeTableCell(route.path)}\``, `\`${escapeTableCell(route.functionName)}\``, 'Active'],
    ...aliasRows,
  ];

  return [
    '### Routes',
    '',
    '| Type | Method | Path | Name | Status |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}

function buildOverviewBlock(def: MethodDefinition): string {
  const meta = def.meta;
  const rows = [
    ['Namespace', `\`${escapeTableCell(meta.namespace ?? 'core')}\``],
    ['Action', meta.action ? `\`${escapeTableCell(meta.action)}\`` : '-'],
    ['Functionality', meta.functionality ? `\`${escapeTableCell(meta.functionality)}\`` : '-'],
    ['Positional parameter order', formatList(meta.parameterOrder)],
    ['Aliases', formatList(sortStrings(meta.allAliases ?? []))],
    ['Deprecated aliases', formatList(sortStrings(meta.deprecatedAliases ?? []))],
    ['License', meta.license ? `\`${escapeTableCell(meta.license)}\`` : '`none`'],
    ['WAPI override', meta.wapiOverride ? `\`${escapeTableCell(meta.wapiOverride)}\`` : '-'],
    ['Deprecated', meta.deprecated ? '**Yes**' : 'No'],
  ];

  return [
    '### Overview',
    '',
    '| Prop | Value |',
    '| --- | --- |',
    ...rows.map(([prop, value]) => `| ${prop} | ${value} |`),
  ].join('\n');
}

function buildLicenseCallout(def: MethodDefinition): string {
  const license = def.meta.license;
  if (!license || license === 'none') {
    return '';
  }

  return `<LicensedFeatureCallout tier="${license}" />`;
}

function buildOutputBlock(outputSummary: string): string {
  return [
    '| Prop | Value |',
    '| --- | --- |',
    `| Return type | \`${escapeTableCell(outputSummary)}\` |`,
  ].join('\n');
}

function decodeMarkdownInline(value: string): string {
  return value.replace(/^`|`$/g, '').replace(/\\`/g, '`').replace(/\\\|/g, '|').replace(/&#123;/g, '{').replace(/&#125;/g, '}');
}

function sampleValueForParameter(row: ParameterRow): string {
  if (row.example !== '-') {
    return decodeMarkdownInline(row.example);
  }

  if (row.type.endsWith('[]')) {
    return '[]';
  }

  if (row.type.includes('number')) {
    return '1';
  }

  if (row.type.includes('boolean')) {
    return 'true';
  }

  if (row.type.startsWith('object') || row.type === 'unknown') {
    return '{}';
  }

  return JSON.stringify(row.name);
}

function buildParameterObject(rows: ParameterRow[], indent: string): string {
  if (rows.length === 0) {
    return '{}';
  }

  return [
    '{',
    ...rows.map((row) => `${indent}${row.name}: ${sampleValueForParameter(row)},`),
    '}',
  ].join('\n');
}

function buildJsonBody(rows: ParameterRow[], indent: string): string {
  if (rows.length === 0) {
    return '{}';
  }

  const entries = rows.map((row) => {
    const sample = sampleValueForParameter(row);
    try {
      return [row.name, JSON.parse(sample)] as const;
    } catch {
      return [row.name, sample] as const;
    }
  });

  return JSON.stringify(Object.fromEntries(entries), null, 2).split('\n').map((line, index) => index === 0 ? line : `${indent}${line}`).join('\n');
}

function buildCurlExample(route: HttpMethodDefinition | undefined, rows: ParameterRow[]): string {
  if (!route) {
    return '# HTTP route is not registered for this method yet.';
  }

  const url = `http://localhost:8080${route.path}`;
  if (route.httpMethod === 'GET' && rows.length > 0) {
    return [
      `curl -G ${JSON.stringify(url)} \\`,
      '  -H "x-api-key: YOUR_API_KEY" \\',
      ...rows.map((row, index) => {
        const suffix = index === rows.length - 1 ? '' : ' \\';
        return `  --data-urlencode ${JSON.stringify(`${row.name}=${sampleValueForParameter(row).replace(/^"|"$/g, '')}`)}${suffix}`;
      }),
    ].join('\n');
  }

  return [
    `curl -X ${route.httpMethod} ${JSON.stringify(url)} \\`,
    '  -H "content-type: application/json" \\',
    '  -H "x-api-key: YOUR_API_KEY" \\',
    `  --data '${buildJsonBody(rows, '  ')}'`,
  ].join('\n');
}

function buildUsageTabs(def: MethodDefinition, route: HttpMethodDefinition | undefined, rows: ParameterRow[]): string {
  const namespace = def.meta.namespace ?? 'core';
  const namespacedName = def.meta.namespacedName ?? def.meta.functionName;
  const parameterObject = buildParameterObject(rows, '  ');

  return [
    '### Usage',
    '',
    '<Tabs items={["Client", "Namespaced client", "HTTP API"]}>',
    '  <Tab value="Client">',
    '',
    '```ts',
    `const result = await client.${def.meta.functionName}(${parameterObject});`,
    '```',
    '',
    '  </Tab>',
    '  <Tab value="Namespaced client">',
    '',
    '```ts',
    `const result = await client.${namespace}.${namespacedName}(${parameterObject});`,
    '```',
    '',
    '  </Tab>',
    '  <Tab value="HTTP API">',
    '',
    '```bash',
    buildCurlExample(route, rows),
    '```',
    '',
    '  </Tab>',
    '</Tabs>',
  ].join('\n');
}

function buildMethodSection(def: MethodDefinition, route: HttpMethodDefinition | undefined): string {
  const outputSummary = summarizeSchema(schemaToJsonSchema(def.meta.outputSchema));
  const parameters = buildParameterRows(def);
  const licenseSuffix = (def.meta.license && def.meta.license !== 'none') ? ` - ${def.meta.license}` : '';
  const licenseCallout = buildLicenseCallout(def);

  const parts = [
    `## \`${def.meta.functionName}\`${licenseSuffix}`,
    '',
    def.meta.description ?? `Client method ${def.meta.functionName}.`,
    '',
    licenseCallout,
    '',
    buildOverviewBlock(def),
    '',
    buildRouteBlock(route),
    '',
    buildUsageTabs(def, route, parameters),
    '',
    '### Parameters',
    '',
    buildParameterTable(def, parameters),
    '',
    '### Output',
    '',
    buildOutputBlock(outputSummary),
  ];

  return parts.filter((part, index) => part !== '' || parts[index - 1] !== '').join('\n');
}

function slugForNamespace(namespace: string): string {
  return namespace.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
}

function writeFileIfChanged(filePath: string, content: string): void {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) {
    return;
  }

  fs.writeFileSync(filePath, content);
}

function cleanGeneratedDocs(): void {
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
    return;
  }

  for (const entry of fs.readdirSync(docsDir)) {
    if (entry.endsWith('.mdx') || entry === 'meta.json' || entry === 'methods-map.json' || entry === 'generated-method-params.ts') {
      fs.rmSync(path.join(docsDir, entry));
    }
  }
}

const methods = clientRegistry
  .getAll()
  .slice()
  .sort((left, right) => left.meta.functionName.localeCompare(right.meta.functionName));
const routesByFunctionName = new Map(
  getHttpMethodDefinitions('/api')
    .slice()
    .sort((left, right) => left.functionName.localeCompare(right.functionName))
    .map((route) => [route.functionName, route])
);
const methodsByNamespace = new Map<string, MethodDefinition[]>();

for (const def of methods) {
  const namespace = def.meta.namespace ?? 'core';
  const namespaceMethods = methodsByNamespace.get(namespace) ?? [];
  namespaceMethods.push(def);
  methodsByNamespace.set(namespace, namespaceMethods);
}

cleanGeneratedDocs();

const namespaces = sortStrings(Array.from(methodsByNamespace.keys()));
const meta = {
  title: 'Client API',
  icon: 'BookOpen',
  pages: ['index', 'client', ...namespaces.map(slugForNamespace)],
};

const indexContent = [
  buildFrontmatter('Client API Reference', 'Generated reference for schema-registry client methods.', 'BookOpen'),
  '',
  '# Client API Reference',
  '',
  buildGeneratedWarning(),
  '',
  'These pages are generated from `packages/schema/src/registry.ts` and `packages/schema/src/methods/*.ts`.',
  '',
  '## Namespaces',
  '',
  '<Cards>',
  '',
  ...namespaces.map((namespace) => {
    const namespaceMethods = methodsByNamespace.get(namespace) ?? [];
    const slug = slugForNamespace(namespace);
    return [
      `  <Card title="${escapeMdxText(titleCase(namespace))}" href="./${slug}">`,
      `    ${namespaceMethods.length} client methods`,
      '  </Card>',
      '',
    ].join('\n');
  }),
  '</Cards>',
].join('\n');

writeFileIfChanged(path.join(docsDir, 'index.mdx'), `${indexContent}\n`);
writeFileIfChanged(path.join(docsDir, 'meta.json'), `${JSON.stringify(meta, null, 2)}\n`);

const clientContent = [
  buildFrontmatter('Client Reference', 'Comprehensive flat client method reference.', 'BookOpen'),
  '',
  '# Client Reference',
  '',
  buildGeneratedWarning(),
  '',
  'This page documents all client methods alphabetically in a single flat namespace for easy reference.',
  '',
  methods.map((def) => buildMethodSection(def, routesByFunctionName.get(def.meta.functionName))).join('\n\n'),
].join('\n');

writeFileIfChanged(path.join(docsDir, 'client.mdx'), `${clientContent}\n`);

for (const namespace of namespaces) {
  const namespaceMethods = methodsByNamespace.get(namespace) ?? [];
  const pageContent = [
    buildFrontmatter(
      `${titleCase(namespace)} Client API`,
      `Generated client method reference for the ${namespace} namespace.`,
      'BookOpen'
    ),
    '',
    `# ${titleCase(namespace)} Client API`,
    '',
    buildGeneratedWarning(),
    '',
    `This page documents ${namespaceMethods.length} schema-registry client methods in the \`${namespace}\` namespace.`,
    '',
    namespaceMethods.map((def) => buildMethodSection(def, routesByFunctionName.get(def.meta.functionName))).join('\n\n'),
  ].join('\n');

  writeFileIfChanged(path.join(docsDir, `${slugForNamespace(namespace)}.mdx`), `${pageContent}\n`);
}

const methodsMap: Record<string, string> = {};
for (const def of methods) {
  const nsSlug = slugForNamespace(def.meta.namespace ?? 'core');
  methodsMap[def.meta.functionName] = `/docs/reference/client/${nsSlug}#${def.meta.functionName.toLowerCase()}`;
}

writeFileIfChanged(path.join(docsDir, 'methods-map.json'), `${JSON.stringify(methodsMap, null, 2)}\n`);

const interfacesContent = buildAllParamsInterfaces(methods);
writeFileIfChanged(path.join(docsDir, 'generated-method-params.ts'), interfacesContent);

console.log(`Successfully generated Client API reference docs with ${methods.length} methods across ${namespaces.length} namespaces plus flat client page, methods map, and parameter interfaces`);
