import fs from 'fs';
import path from 'path';
import { Registry } from '../src/registry';
import '../src/methods';

const generatedDir = path.join(__dirname, '../src/generated');
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}

let output = `/* eslint-disable */
/**
 * This file was automatically generated by packages/schema/scripts/gen-client-implementation.ts
 * Do not edit this file manually.
 */
import * as Types from './types';
import { Registry } from '../registry';

export abstract class BaseClient {
  protected abstract execute(method: string, args: any): Promise<any>;

`;

const methods = Registry.getAllMethods();

methods.forEach((method) => {
    const inputType = `Types.${capitalize(method.name)}Input`;
    const outputType = `Types.${capitalize(method.name)}Output`;

    // Method implementation
    output += `
  /**
   * ${method.metadata.description}
   * @param args - ${inputType}
   */
  async ${method.name}(args: ${inputType}): Promise<${outputType}> {
    const methodDef = Registry.getMethod('${method.name}');
    if (!methodDef) throw new Error('Method ${method.name} not found in registry');
    
    // Validate input
    const validatedArgs = methodDef.inputSchema.parse(args);
    
    // Execute
    const result = await this.execute('${method.name}', validatedArgs);
    
    // Validate output
    return methodDef.outputSchema.parse(result);
  }
`;
});

output += `}
`;

fs.writeFileSync(path.join(generatedDir, 'BaseClient.ts'), output);
console.log('Successfully generated BaseClient.ts');

function capitalize(s: string) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
