import fs from 'fs';
import path from 'path';
import { clientRegistry } from '../src/registry';
import '../src/methods'; // Ensure methods are registered

// Create generated directory
import { fileURLToPath } from "node:url";
const generatedDir = path.join(fileURLToPath(new URL(".", import.meta.url)), '../src/generated');
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}

let output = `/* eslint-disable */
/**
 * This file was automatically generated by packages/schema/scripts/gen-types.ts
 * Do not edit this file manually.
 */

import type * as Zod from 'zod';
import type * as Methods from '../methods';
`;

// Generate types for all methods
const methods = clientRegistry.getAll();

methods.forEach((method) => {
    const name = method.meta.functionName;
    const inputIdentifier = `${capitalize(name)}Input`;
    const outputIdentifier = `${capitalize(name)}Output`;

    output += `
export type ${inputIdentifier} = Zod.input<typeof Methods.${name}.openWAInput>;
export type ${outputIdentifier} = Zod.output<typeof Methods.${name}.openWAOutput>;
`;
});

// Write types.ts
fs.writeFileSync(path.join(generatedDir, 'types.ts'), output);
console.log('Successfully generated types.ts');

function capitalize(s: string) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
