name: Publish Package to custom registry
on:
  workflow_dispatch:
  push:
    branches: [production]
    tags:
      - 'v*'
  # pull_request:
  #   branches:
  #     - main
  #     - production
  #   types: [opened, reopened]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm ci
      - run: npm i -g npm-cli-login
      - run: npm-cli-login -u ${{secrets.NPM_USERNAME}} -p ${{secrets.NPM_PASSWORD}} -e ${{secrets.NPM_EMAIL}} -r ${{ secrets.NPM_REGISTRY }} --config-path /home/runner/work/_temp/.npmrc
      - run: npm run build
      - run: npm publish